NEXT_PUBLIC_API_URL="https://api.letsworkwise.com/api/v1"
PORT=8001
NEXT_PUBLIC_SERVICEWORKER_PUBLIC_KEY="BMlcHp3X2DtYmsKkev81HR4CJeOqxTyLEZC0JU3Fnxi7qaKqM7-qOWvgPCb4Q9FmFW6-hyc9AG4w4BtrHTkwO2c"
NEXT_PUBLIC_RAZORPAY_KEY="rzp_test_dqkSkuFKnzKXKO"
NEXT_PUBLIC_RAZORPAY_SECRET="xYy0gXNEHHO6dNkHztO8mUZd"
NEXT_PUBLIC_RAZORPAY_SIGNATURE="De$@af%^&HGk"


