export const blogData = [
    {
      id: 1,
      image: "https://picsum.photos/200/300",
      title: "Blog Title1", 
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget sapien egestas tincidunt. Nullam nec nunc nec nunc."
    },
    {
      id: 2,
      image: "https://picsum.photos/200/300",
      title: "Blog Title2", 
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget sapien egestas tincidunt. Nullam nec nunc nec nunc."
    },
    {
      id: 3,
      image: "https://picsum.photos/200/300",
      title: "Blog Title3",  
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget sapien egestas tincidunt. Nullam nec nunc nec nunc."
    }
    
  ]

  export const products = [
    { id: 1, image: "https://picsum.photos/200/300", title: "Product Name1" },
    { id: 2, image: "https://picsum.photos/200/300", title: "Product Name2" },
    { id: 3, image: "https://picsum.photos/200/300", title: "Product Name3" },
    { id: 4, image: "https://picsum.photos/200/300", title: "Product Name4" },
    { id: 5, image: "https://picsum.photos/200/300", title: "Product Name5" },
    { id: 6, image: "https://picsum.photos/200/300", title: "Product Name6" },
    { id: 7, image: "https://picsum.photos/200/300", title: "Product Name7" },
  ];


  export const CATEGORIES = [
    { id: 'mechanical', name: 'Mechanical', image: 'https://picsum.photos/200/300' },
    { id: 'electrical', name: 'Electrical', image: 'https://picsum.photos/200/300' },
    { id: 'chemical', name: 'Chemical', image: 'https://picsum.photos/200/300' },
    { id: 'fire-engineering', name: 'Fire Engineering', image: 'https://picsum.photos/200/300' },
    { id: 'mineral', name: 'Mineral', image: 'https://picsum.photos/200/300' },
    { id: 'it', name: 'IT', image: 'https://picsum.photos/200/300' },
    { id: 'civil', name: 'Civil', image: 'https://picsum.photos/200/300' },
  ];
  
  export const SUBCATEGORIES = {
    'mechanical': [
      { id: 'valves', name: 'Valves', image: 'https://picsum.photos/200/300' },
      { id: 'pipe-fittings', name: 'Pipe Fittings', image: 'https://picsum.photos/200/300' },
      { id: 'pumps', name: 'Pumps', image: 'https://picsum.photos/200/300' },
      { id: 'bearings', name: 'Bearings', image: 'https://picsum.photos/200/300' },
      { id: 'engines', name: 'Engines', image: 'https://picsum.photos/200/300' },
    ],
    'electrical': [
      { id: 'switches', name: 'Switches', image: 'https://picsum.photos/200/300' },
      { id: 'wires', name: 'Wires', image: 'https://picsum.photos/200/300' },
      { id: 'connectors', name: 'Connectors', image: 'https://picsum.photos/200/300' },
      { id: 'transformers', name: 'Transformers', image: 'https://picsum.photos/200/300' },
      { id: 'power-supplies', name: 'Power Supplies', image: 'https://picsum.photos/200/300' },
    ],
    'chemical': [
      { id: 'acids', name: 'Acids', image: 'https://picsum.photos/200/300' },
      { id: 'bases', name: 'Bases', image: 'https://picsum.photos/200/300' },
      { id: 'solvents', name: 'Solvents', image: 'https://picsum.photos/200/300' },
      { id: 'polymers', name: 'Polymers', image: 'https://picsum.photos/200/300' },
      { id: 'catalysts', name: 'Catalysts', image: 'https://picsum.photos/200/300' },
    ],
    'fire-engineering': [
      { id: 'fire-extinguishers', name: 'Fire Extinguishers', image: 'https://picsum.photos/200/300' },
      { id: 'sprinklers', name: 'Sprinklers', image: 'https://picsum.photos/200/300' },
      { id: 'smoke-detectors', name: 'Smoke Detectors', image: 'https://picsum.photos/200/300' },
      { id: 'fire-alarms', name: 'Fire Alarms', image: 'https://picsum.photos/200/300' },
      { id: 'fire-hoses', name: 'Fire Hoses', image: 'https://picsum.photos/200/300' },
    ],
    'mineral': [
      { id: 'ores', name: 'Ores', image: 'https://picsum.photos/200/300' },
      { id: 'metals', name: 'Metals', image: 'https://picsum.photos/200/300' },
      { id: 'stones', name: 'Stones', image: 'https://picsum.photos/200/300' },
      { id: 'salts', name: 'Salts', image: 'https://picsum.photos/200/300' },
      { id: 'clays', name: 'Clays', image: 'https://picsum.photos/200/300' },
    ],
    'it': [
      { id: 'servers', name: 'Servers', image: 'https://picsum.photos/200/300' },
      { id: 'routers', name: 'Routers', image: 'https://picsum.photos/200/300' },
      { id: 'software', name: 'Software', image: 'https://picsum.photos/200/300' },
      { id: 'hardware', name: 'Hardware', image: 'https://picsum.photos/200/300' },
      { id: 'databases', name: 'Databases', image: 'https://picsum.photos/200/300' },
    ],
  };

  export const BusinessTypes = [
      {value : "authorised Distributor", label : "Authorised Distributor"},
      {value : "authorised Dealer", label : "Authorised Dealer"},
      {value : "branch", label : "Branch"},
      {value : "channel partner", label : "Channel Partner"},
      {value : "distributor", label : "Distributor"},
      {value : "constructor", label : "Constructor"},
      {value : "contractor", label : "Contractor"},
      {value : "dealer", label: "Dealer" },
      {value : "designer", label : "Designer"},
      {value : "exporter", label : "Exporter"},
      {value : "importer", label : "Importer"},
      {value : 'manufacturer', label: 'Manufacturer' },
      {value : "oem (original equipment manufacturer)", label : "OEM (Original Equipment Manufacturer)"},
      {value : "official distributor", label : "Official Distributor"},
      {value : "partner", label : "Partner"},
      {value : "retailer", label : "Retailer"},
      {value : "service Provider", label : "Service Provider"},
      {value : "supplier", label : "Supplier"},
      {value : "subsidiary" , label : 'Subsidiary'},
      {value : "stockist", label : "Stockist"},
      {value : "trader", label : "Trader"},
      {value: 'wholesaler', label: 'Wholesaler' } 
];

export const ALLOWED_PO_USERS = [2, 7, 8, 10]


export const State_Cities = [
  {
    state_id: 234,
    state_name: "Abu Dhabi",
    cities: [{ id: 1548, name: "Abu Dhabi" }],
  },
  {
    state_id: 224,
    state_name: "Alabama",
    cities: [{ id: 1517, name: "Pelham" }],
  },
  {
    state_id: 84,
    state_name: "Andaman and Nicobar Islands",
    cities: [
      { id: 1, name: "Port Blair" },
      { id: 1251, name: "Rangat" },
    ],
  },
  {
    state_id: 93,
    state_name: "Andhra Pradesh",
    cities: [
      { id: 227, name: "Adoni" },
      { id: 1763, name: "Agiripalli" },
      { id: 268, name: "Amalapuram" },
      { id: 246, name: "Anakapalle" },
      { id: 221, name: "Anantapur" },
      { id: 253, name: "Bapatla" },
      { id: 269, name: "Bheemunipatnam" },
      { id: 232, name: "Bhimavaram" },
      { id: 263, name: "Bobbili" },
      { id: 1331, name: "Cheepurupalli" },
      { id: 242, name: "Chilakaluripet" },
      { id: 245, name: "Chirala" },
      { id: 229, name: "Chittoor" },
      { id: 1337, name: "Cumbum" },
      { id: 234, name: "Dharmavaram" },
      { id: 1756, name: "East Godavari" },
      { id: 223, name: "Eluru" },
      { id: 276, name: "Gooty" },
      { id: 235, name: "Gudivada" },
      { id: 256, name: "Gudur" },
      { id: 237, name: "Guntakal" },
      { id: 214, name: "Guntur" },
      { id: 231, name: "Hindupur" },
      { id: 266, name: "Jaggaiahpet" },
      { id: 279, name: "Jammalamadugu" },
      { id: 220, name: "Kadapa" },
      { id: 244, name: "Kadiri" },
      { id: 217, name: "Kakinada" },
      { id: 262, name: "Kandukur" },
      { id: 247, name: "Kavali" },
      { id: 285, name: "Kovvur" },
      { id: 1692, name: "Kuppam" },
      { id: 216, name: "Kurnool" },
      { id: 275, name: "Macherla" },
      { id: 226, name: "Machilipatnam" },
      { id: 233, name: "Madanapalle" },
      { id: 278, name: "Mandapeta" },
      { id: 260, name: "Markapur" },
      { id: 254, name: "Nagari" },
      { id: 255, name: "Naidupet" },
      { id: 225, name: "Nandyal" },
      { id: 1409, name: "Narasannapeta" },
      { id: 258, name: "Narasapuram" },
      { id: 238, name: "Narasaraopet" },
      { id: 288, name: "Narsipatnam" },
      { id: 215, name: "Nellore" },
      { id: 282, name: "Nidadavole" },
      { id: 259, name: "Nuzvid" },
      { id: 224, name: "Ongole" },
      { id: 248, name: "Palacole" },
      { id: 273, name: "Palasa Kasibugga" },
      { id: 274, name: "Parvathipuram" },
      { id: 290, name: "Pedana" },
      { id: 281, name: "Peddapuram" },
      { id: 272, name: "Pithapuram" },
      { id: 261, name: "Ponnur" },
      { id: 230, name: "Proddatur" },
      { id: 280, name: "Punganur" },
      { id: 291, name: "Puttur" },
      { id: 218, name: "Rajahmundry" },
      { id: 292, name: "Rajam" },
      { id: 1393, name: "Rajamahendravaram" },
      { id: 239, name: "Rajampet" },
      { id: 284, name: "Ramachandrapuram" },
      { id: 1761, name: "Ravulapalem" },
      { id: 251, name: "Rayachoti" },
      { id: 264, name: "Rayadurg" },
      { id: 293, name: "Renigunta" },
      { id: 283, name: "Repalle" },
      { id: 277, name: "Salur" },
      { id: 265, name: "Samalkot" },
      { id: 270, name: "Sattenapalle" },
      { id: 236, name: "Srikakulam" },
      { id: 252, name: "Srikalahasti" },
      { id: 295, name: "Srisailam Project (Right Flank Colony) Township" },
      { id: 249, name: "Sullurpeta" },
      { id: 240, name: "Tadepalligudem" },
      { id: 241, name: "Tadpatri" },
      { id: 250, name: "Tanuku" },
      { id: 228, name: "Tenali" },
      { id: 219, name: "Tirupati" },
      { id: 286, name: "Tiruvuru" },
      { id: 267, name: "Tuni" },
      { id: 287, name: "Uravakonda" },
      { id: 271, name: "Venkatagiri" },
      { id: 213, name: "Vijayawada" },
      { id: 257, name: "Vinukonda" },
      { id: 212, name: "Visakhapatnam" },
      { id: 222, name: "Vizianagaram" },
      { id: 1762, name: "West Godavari" },
      { id: 243, name: "Yemmiganur" },
      { id: 289, name: "Yerraguntla" },
    ],
  },
  {
    state_id: 197,
    state_name: "Angoumois",
    cities: [{ id: 1455, name: "Angoulême" }],
  },
  {
    state_id: 199,
    state_name: "Anjou",
    cities: [{ id: 1459, name: "Verrières-en-anjou" }],
  },
  {
    state_id: 206,
    state_name: "Antwerp",
    cities: [{ id: 1471, name: "Lier" }],
  },
  {
    state_id: 281,
    state_name: "Arizona",
    cities: [{ id: 1696, name: "Phoenix" }],
  },
  {
    state_id: 114,
    state_name: "Arunachal Pradesh",
    cities: [
      { id: 1054, name: "Naharlagun" },
      { id: 1055, name: "Pasighat" },
    ],
  },
  {
    state_id: 97,
    state_name: "Assam",
    cities: [
      { id: 513, name: "Barpeta" },
      { id: 504, name: "Bongaigaon City" },
      { id: 505, name: "Dhubri" },
      { id: 500, name: "Dibrugarh" },
      { id: 506, name: "Diphu" },
      { id: 1765, name: "Duliajan" },
      { id: 511, name: "Goalpara" },
      { id: 1532, name: "Golaghat" },
      { id: 497, name: "Guwahati" },
      { id: 1578, name: "Hojai" },
      { id: 502, name: "Jorhat" },
      { id: 509, name: "Karimganj" },
      { id: 512, name: "Lanka" },
      { id: 514, name: "Lumding" },
      { id: 519, name: "Mangaldoi" },
      { id: 515, name: "Mankachar" },
      { id: 518, name: "Margherita" },
      { id: 521, name: "Mariani" },
      { id: 523, name: "Marigaon" },
      { id: 501, name: "Nagaon" },
      { id: 516, name: "Nalbari" },
      { id: 507, name: "North Lakhimpur" },
      { id: 517, name: "Rangia" },
      { id: 510, name: "Sibsagar" },
      { id: 520, name: "Silapathar" },
      { id: 499, name: "Silchar" },
      { id: 508, name: "Tezpur" },
      { id: 503, name: "Tinsukia" },
    ],
  },
  {
    state_id: 233,
    state_name: "Auvergne-rhône-alpes",
    cities: [
      { id: 1588, name: "Chambéry" },
      { id: 1547, name: "Lyon" },
    ],
  },
  {
    state_id: 118,
    state_name: "Badakhshan",
    cities: [{ id: null, name: null }],
  },
  {
    state_id: 161,
    state_name: "Baden-württemberg",
    cities: [
      { id: 1666, name: "Bretten" },
      { id: 1568, name: "Heidelberg" },
      { id: 1529, name: "Mannheim" },
      { id: 1346, name: "Metzingen" },
      { id: 1742, name: "Obersontheim" },
      { id: 1445, name: "Rheinfelden (aargau)" },
      { id: 1671, name: "Schopfheim" },
      { id: 1492, name: "Steinheim Am Albuch" },
      { id: 1512, name: "Stuttgart" },
      { id: 1432, name: "Ulm" },
      { id: 1783, name: "Weil Am Rhein" },
      { id: 1609, name: "Wertheim Am Main" },
    ],
  },
  {
    state_id: 261,
    state_name: "Bagmati",
    cities: [{ id: 1635, name: "Kathmandu" }],
  },
  {
    state_id: 205,
    state_name: "Bangkok",
    cities: [{ id: 1470, name: "Bangkok" }],
  },
  {
    state_id: 219,
    state_name: "Bavaria",
    cities: [
      { id: 1708, name: "Herzogenaurach" },
      { id: 1787, name: "Kitzingen" },
      { id: 1502, name: "Munich" },
    ],
  },
  {
    state_id: 255,
    state_name: "Bedfordshire",
    cities: [{ id: 1614, name: "Kempston" }],
  },
  {
    state_id: 120,
    state_name: "Beijing Municipality",
    cities: [
      { id: 1259, name: "Beijing" },
      { id: 1257, name: "Wuqing" },
    ],
  },
  {
    state_id: 132,
    state_name: "Belgian Limburg",
    cities: [
      { id: 1283, name: "Oudsbergen" },
      { id: 1304, name: "Tessenderlo" },
    ],
  },
  {
    state_id: 128,
    state_name: "Bergamo (bg)",
    cities: [
      { id: 1279, name: "Bergamo" },
      { id: 1479, name: "Seriate" },
    ],
  },
  {
    state_id: 292,
    state_name: "Berlin",
    cities: [{ id: 1741, name: "Berlin" }],
  },
  {
    state_id: 109,
    state_name: "bihar",
    cities: [
      { id: 891, name: "Araria" },
      { id: 868, name: "Arrah" },
      { id: 899, name: "Arwal" },
      { id: 932, name: "Asarganj" },
      { id: 886, name: "Aurangabad" },
      { id: 880, name: "Bagaha" },
      { id: 931, name: "Barh" },
      { id: 870, name: "Begusarai" },
      { id: 878, name: "Bettiah" },
      { id: 1482, name: "Bhabua" },
      { id: 901, name: "BhabUrban Agglomeration" },
      { id: 866, name: "Bhagalpur" },
      { id: 1324, name: "Bihar Sharif" },
      { id: 884, name: "Buxar" },
      { id: 869, name: "Chhapra" },
      { id: 867, name: "Darbhanga" },
      { id: 875, name: "Dehri-on-Sone" },
      { id: 898, name: "Dumraon" },
      { id: 900, name: "Forbesganj" },
      { id: 865, name: "Gaya" },
      { id: 892, name: "Gopalganj" },
      { id: 877, name: "Hajipur" },
      { id: 883, name: "Jamalpur" },
      { id: 889, name: "Jamui" },
      { id: 885, name: "Jehanabad" },
      { id: 871, name: "Katihar" },
      { id: 882, name: "Kishanganj" },
      { id: 887, name: "Lakhisarai" },
      { id: 924, name: "Lalganj" },
      { id: 904, name: "Madhepura" },
      { id: 893, name: "Madhubani" },
      { id: 928, name: "Maharajganj" },
      { id: 910, name: "Mahnar Bazar" },
      { id: 916, name: "Makhdumpur" },
      { id: 918, name: "Maner" },
      { id: 927, name: "Manihari" },
      { id: 922, name: "Marhaura" },
      { id: 895, name: "Masaurhi" },
      { id: 923, name: "Mirganj" },
      { id: 896, name: "Mokameh" },
      { id: 879, name: "Motihari" },
      { id: 926, name: "Motipur" },
      { id: 872, name: "Munger" },
      { id: 925, name: "Murliganj" },
      { id: 864, name: "Muzaffarpur" },
      { id: 902, name: "Narkatiaganj" },
      { id: 903, name: "Naugachhia" },
      { id: 888, name: "Nawada" },
      { id: 919, name: "Nokha" },
      { id: 863, name: "Patna" },
      { id: 920, name: "Piro" },
      { id: 873, name: "Purnia" },
      { id: 921, name: "Rafiganj" },
      { id: 912, name: "Rajgir" },
      { id: 907, name: "Ramnagar" },
      { id: 908, name: "Raxaul Bazar" },
      { id: 911, name: "Revelganj" },
      { id: 917, name: "Rosera" },
      { id: 874, name: "Saharsa" },
      { id: 894, name: "Samastipur" },
      { id: 876, name: "Sasaram" },
      { id: 905, name: "Sheikhpura" },
      { id: 929, name: "Sheohar" },
      { id: 914, name: "Sherghati" },
      { id: 930, name: "Silao" },
      { id: 890, name: "Sitamarhi" },
      { id: 881, name: "Siwan" },
      { id: 913, name: "Sonepur" },
      { id: 915, name: "Sugauli" },
      { id: 906, name: "Sultanganj" },
      { id: 897, name: "Supaul" },
      { id: 909, name: "Warisaliganj" },
    ],
  },
  {
    state_id: 217,
    state_name: "Bologna",
    cities: [{ id: 1499, name: "Calderara Di Reno" }],
  },
  {
    state_id: 225,
    state_name: "Bremen",
    cities: [{ id: 1519, name: "Bremen" }],
  },
  {
    state_id: 145,
    state_name: "Brescia",
    cities: [{ id: 1316, name: "Brescia" }],
  },
  {
    state_id: 299,
    state_name: "Brussels",
    cities: [{ id: 1774, name: "Brussels" }],
  },
  {
    state_id: 165,
    state_name: "Buckinghamshire",
    cities: [{ id: 1372, name: "High Wycombe" }],
  },
  {
    state_id: 160,
    state_name: "California",
    cities: [
      { id: 1460, name: "Corona" },
      { id: 1345, name: "Los Angeles" },
      { id: 1392, name: "San Jose" },
    ],
  },
  {
    state_id: 166,
    state_name: "Cambridgeshire",
    cities: [{ id: 1373, name: "Peterborough" }],
  },
  {
    state_id: 263,
    state_name: "Canton Of Zurich",
    cities: [
      { id: 1700, name: "Oberglatt" },
      { id: 1637, name: "Zurich" },
    ],
  },
  {
    state_id: 136,
    state_name: "Central Southern Liaoning",
    cities: [{ id: 1287, name: "Yingkou" }],
  },
  {
    state_id: 86,
    state_name: "Chandigarh",
    cities: [
      { id: 56, name: "Chandigarh" },
      { id: 1298, name: "Raipur" },
    ],
  },
  {
    state_id: 280,
    state_name: "Cheshire",
    cities: [{ id: 1695, name: "Macclesfield" }],
  },
  {
    state_id: 99,
    state_name: "Chhattisgarh",
    cities: [
      { id: 565, name: "Ambikapur" },
      { id: 569, name: "Bhatapara" },
      { id: 1248, name: "Bhilai" },
      { id: 558, name: "Bhilai Nagar" },
      { id: 560, name: "Bilaspur" },
      { id: 1243, name: "Chawardhal" },
      { id: 567, name: "Chirmiri" },
      { id: 570, name: "Dalli-Rajhara" },
      { id: 568, name: "Dhamtari" },
      { id: 561, name: "Durg" },
      { id: 562, name: "Jagdalpur" },
      { id: 1554, name: "Jashpur Nagar" },
      { id: 1509, name: "Kawardha" },
      { id: 559, name: "Korba" },
      { id: 566, name: "Mahasamund" },
      { id: 573, name: "Manendragarh" },
      { id: 572, name: "Mungeli" },
      { id: 571, name: "Naila Janjgir" },
      { id: 564, name: "Raigarh" },
      { id: 557, name: "Raipur" },
      { id: 563, name: "Rajnandgaon" },
      { id: 575, name: "Sakti" },
      { id: 574, name: "Tilda Newra" },
    ],
  },
  {
    state_id: 223,
    state_name: "Chungcheongnam-do",
    cities: [{ id: 1516, name: "Dangjin" }],
  },
  {
    state_id: 131,
    state_name: "Colorado",
    cities: [
      { id: 1699, name: "Arvada" },
      { id: 1737, name: "Littleton" },
      { id: 1282, name: "Loveland" },
    ],
  },
  {
    state_id: 175,
    state_name: "Columbia",
    cities: [
      { id: 1418, name: "Richmond" },
      { id: 1419, name: "Vancouver" },
    ],
  },
  {
    state_id: 191,
    state_name: "Como(co)",
    cities: [{ id: 1448, name: "Appiano Gentile" }],
  },
  {
    state_id: 275,
    state_name: "Connecticut",
    cities: [
      { id: 1684, name: "Bridgeport" },
      { id: 1710, name: "Bristol" },
      { id: 1718, name: "Newtown" },
      { id: 1745, name: "Waterbury" },
    ],
  },
  {
    state_id: 284,
    state_name: "Copenhagen",
    cities: [{ id: 1719, name: "Copenhagen" }],
  },
  {
    state_id: 208,
    state_name: "Cremona",
    cities: [
      { id: 1475, name: "Malagnino" },
      { id: 1486, name: "Ricengo" },
    ],
  },
  {
    state_id: 104,
    state_name: "Dadra and Nagar Haveli",
    cities: [{ id: null, name: null }],
  },
  {
    state_id: 163,
    state_name: "Delaware",
    cities: [{ id: 1351, name: "Newark" }],
  },
  {
    state_id: 105,
    state_name: "Delhi",
    cities: [
      { id: 723, name: "Delhi" },
      { id: 721, name: "New Delhi" },
      { id: 1399, name: "South Delhi" },
    ],
  },
  {
    state_id: 283,
    state_name: "Derbyshire",
    cities: [
      { id: 1707, name: "Bakewell" },
      { id: 1776, name: "Chesterfield" },
    ],
  },
  {
    state_id: 226,
    state_name: "Dnipropetrovsk",
    cities: [{ id: 1521, name: "Dnipro" }],
  },
  {
    state_id: 142,
    state_name: "Dorset",
    cities: [{ id: 1292, name: "Poole" }],
  },
  { state_id: 147, state_name: "Dubai", cities: [{ id: 1295, name: "Dubai" }] },
  {
    state_id: 300,
    state_name: "Durham",
    cities: [
      { id: 1780, name: "Billingham" },
      { id: 1788, name: "Shildon" },
    ],
  },
  {
    state_id: 188,
    state_name: "Eastern Province",
    cities: [{ id: 1444, name: "Al Jubail" }],
  },
  {
    state_id: 140,
    state_name: "East Sussex",
    cities: [{ id: 1291, name: "Crowborough" }],
  },
  {
    state_id: 256,
    state_name: "East Sussex",
    cities: [{ id: 1615, name: "Hailsham" }],
  },
  {
    state_id: 232,
    state_name: "Emilia-romagna",
    cities: [
      { id: 1594, name: "Piacenza" },
      { id: 1546, name: "Reggio Emilia" },
    ],
  },
  {
    state_id: 155,
    state_name: "Flanders",
    cities: [{ id: 1308, name: "Tessenderlo" }],
  },
  {
    state_id: 290,
    state_name: "Flemish Brabant",
    cities: [{ id: 1738, name: "Zellik" }],
  },
  {
    state_id: 249,
    state_name: "Florence",
    cities: [{ id: 1601, name: "Firenze (florence)" }],
  },
  {
    state_id: 174,
    state_name: "Florida",
    cities: [
      { id: 1670, name: "Deerfield Beach" },
      { id: 1417, name: "Orlando" },
      { id: 1558, name: "Ponte Vedra Beach" },
    ],
  },
  {
    state_id: 270,
    state_name: "Florida",
    cities: [{ id: 1726, name: "Jacksonville" }],
  },
  {
    state_id: 221,
    state_name: "Gauteng",
    cities: [
      { id: 1511, name: "Benoni" },
      { id: 1560, name: "Johannesburg" },
    ],
  },
  {
    state_id: 288,
    state_name: "Georgia",
    cities: [{ id: 1723, name: "Atlanta" }],
  },
  {
    state_id: 244,
    state_name: "Gipuzkoa",
    cities: [{ id: 1593, name: "Idiazabal" }],
  },
  {
    state_id: 200,
    state_name: "Gloucestershire",
    cities: [{ id: 1462, name: "Gloucester" }],
  },
  {
    state_id: 115,
    state_name: "Goa",
    cities: [
      { id: 1260, name: "Bardez" },
      { id: 1701, name: "Curchorem (kudchade)" },
      { id: 1053, name: "Mapusa" },
      { id: 1052, name: "Margao" },
      { id: 1048, name: "Marmagao" },
      { id: 1754, name: "North Goa" },
      { id: 1051, name: "Panaji" },
      { id: 1751, name: "Pernem" },
      { id: 1550, name: "Ponda" },
      { id: 1623, name: "Sanguem" },
      { id: 1764, name: "South Goa" },
      { id: 1703, name: "Tiswadi" },
      { id: 1272, name: "Vasco Da Gama" },
      { id: 1757, name: "Verna" },
    ],
  },
  {
    state_id: 272,
    state_name: "Goriška",
    cities: [{ id: 1679, name: "Tolmin" }],
  },
  {
    state_id: 282,
    state_name: "Greater Manchester",
    cities: [{ id: 1698, name: "Stockport" }],
  },
  {
    state_id: 141,
    state_name: "Groningen",
    cities: [{ id: null, name: null }],
  },
  {
    state_id: 121,
    state_name: "Guangdong",
    cities: [
      { id: 1297, name: "Dongguan" },
      { id: 1258, name: "Shenzhen" },
      { id: 1659, name: "Yangjiang" },
    ],
  },
  {
    state_id: 111,
    state_name: "Gujarat",
    cities: [
      { id: 1002, name: "Adalaj" },
      { id: 1772, name: "Adipur" },
      { id: 933, name: "Ahmedabad" },
      { id: 953, name: "Amreli" },
      { id: 941, name: "Anand" },
      { id: 955, name: "Anjar" },
      { id: 961, name: "Ankleshwar" },
      { id: 944, name: "Bharuch" },
      { id: 937, name: "Bhavnagar" },
      { id: 948, name: "Bhuj" },
      { id: 1704, name: "Bilimora" },
      { id: 1728, name: "Bodeli" },
      { id: 1004, name: "Chhapra" },
      { id: 1706, name: "Dahegam" },
      { id: 1752, name: "Dahod" },
      { id: 954, name: "Deesa" },
      { id: 957, name: "Dhoraji" },
      { id: 1226, name: "Gandhidham" },
      { id: 1005, name: "Gandhinagar" },
      { id: 950, name: "Godhra" },
      { id: 1242, name: "Halol" },
      { id: 1626, name: "Himatnagar" },
      { id: 938, name: "Jamnagar" },
      { id: 963, name: "Kadi" },
      { id: 1252, name: "Kalol" },
      { id: 974, name: "Kapadvanj" },
      { id: 960, name: "Keshod" },
      { id: 956, name: "Khambhat" },
      { id: 1758, name: "Kheda" },
      { id: 1003, name: "Lathi" },
      { id: 977, name: "Limbdi" },
      { id: 982, name: "Lunawada" },
      { id: 989, name: "Mahemdabad" },
      { id: 942, name: "Mahesana" },
      { id: 958, name: "Mahuva" },
      { id: 996, name: "Manavadar" },
      { id: 980, name: "Mandvi" },
      { id: 969, name: "Mangrol" },
      { id: 991, name: "Mansa" },
      { id: 971, name: "Modasa" },
      { id: 943, name: "Morvi" },
      { id: 1580, name: "Mundra" },
      { id: 940, name: "Nadiad" },
      { id: 946, name: "Navsari" },
      { id: 981, name: "Padra" },
      { id: 949, name: "Palanpur" },
      { id: 972, name: "Palitana" },
      { id: 1000, name: "Pardi" },
      { id: 952, name: "Patan" },
      { id: 973, name: "Petlad" },
      { id: 939, name: "Porbandar" },
      { id: 988, name: "Radhanpur" },
      { id: 936, name: "Rajkot" },
      { id: 983, name: "Rajpipla" },
      { id: 987, name: "Rajula" },
      { id: 990, name: "Ranavav" },
      { id: 999, name: "Rapar" },
      { id: 997, name: "Salaya" },
      { id: 986, name: "Sanand" },
      { id: 962, name: "Savarkundla" },
      { id: 967, name: "Sidhpur" },
      { id: 975, name: "Sihor" },
      { id: 720, name: "Silvassa" },
      { id: 1001, name: "Songadh" },
      { id: 934, name: "Surat" },
      { id: 1630, name: "Surendranagar" },
      { id: 994, name: "Talaja" },
      { id: 979, name: "Thangadh" },
      { id: 992, name: "Tharad" },
      { id: 993, name: "Umbergaon" },
      { id: 985, name: "Umreth" },
      { id: 966, name: "Una" },
      { id: 968, name: "Unjha" },
      { id: 965, name: "Upleta" },
      { id: 995, name: "Vadnagar" },
      { id: 935, name: "Vadodara" },
      { id: 951, name: "Valsad" },
      { id: 984, name: "Vapi" },
      { id: 945, name: "Vapi" },
      { id: 947, name: "Veraval" },
      { id: 998, name: "Vijapur" },
      { id: 970, name: "Viramgam" },
      { id: 964, name: "Visnagar" },
      { id: 978, name: "Vyara" },
      { id: 959, name: "Wadhwan" },
      { id: 976, name: "Wankaner" },
    ],
  },
  {
    state_id: 190,
    state_name: "Gyeonggi",
    cities: [
      { id: 1584, name: "Hwaseong-si" },
      { id: 1746, name: "Incheon" },
      { id: 1493, name: "Seongnam-si" },
      { id: 1447, name: "Seoul" },
      { id: 1456, name: "Siheung" },
      { id: 1717, name: "Yeoju-si" },
    ],
  },
  {
    state_id: 172,
    state_name: "Hampshire",
    cities: [{ id: 1390, name: "Havant" }],
  },
  {
    state_id: 94,
    state_name: "Haryana",
    cities: [
      { id: 1236, name: "Ambala" },
      { id: 387, name: "Bahadurgarh" },
      { id: 386, name: "Bhiwani" },
      { id: 401, name: "Charkhi Dadri" },
      { id: 1328, name: "Cheeka" },
      { id: 377, name: "Faridabad" },
      { id: 396, name: "Fatehabad" },
      { id: 1538, name: "Gharaunda" },
      { id: 397, name: "Gohana" },
      { id: 378, name: "Gurgaon" },
      { id: 394, name: "Hansi" },
      { id: 379, name: "Hisar" },
      { id: 1753, name: "Jhajjar" },
      { id: 388, name: "Jind" },
      { id: 391, name: "Kaithal" },
      { id: 382, name: "Karnal" },
      { id: 406, name: "Ladwa" },
      { id: 410, name: "Mahendragarh" },
      { id: 400, name: "Mandi Dabwali" },
      { id: 395, name: "Narnaul" },
      { id: 398, name: "Narwana" },
      { id: 393, name: "Palwal" },
      { id: 385, name: "Panchkula" },
      { id: 380, name: "Panipat" },
      { id: 402, name: "Pehowa" },
      { id: 1405, name: "Pinangwan" },
      { id: 404, name: "Pinjore" },
      { id: 413, name: "Rania" },
      { id: 411, name: "Ratia" },
      { id: 392, name: "Rewari" },
      { id: 381, name: "Rohtak" },
      { id: 407, name: "Safidon" },
      { id: 405, name: "Samalkha" },
      { id: 412, name: "Sarsod" },
      { id: 403, name: "Shahbad" },
      { id: 389, name: "Sirsa" },
      { id: 409, name: "Sohna" },
      { id: 383, name: "Sonipat" },
      { id: 408, name: "Taraori" },
      { id: 390, name: "Thanesar" },
      { id: 399, name: "Tohana" },
      { id: 384, name: "Yamunanagar" },
    ],
  },
  {
    state_id: 278,
    state_name: "Heilongjiang",
    cities: [{ id: 1691, name: "Harbin" }],
  },
  {
    state_id: 293,
    state_name: "Hertfordshire",
    cities: [{ id: 1744, name: "Baldock" }],
  },
  {
    state_id: 133,
    state_name: "Hesse",
    cities: [
      { id: 1689, name: "Bensheim" },
      { id: 1570, name: "Frankfurt Am Main" },
      { id: 1284, name: "Kassel" },
      { id: 1496, name: "Stadtallendorf" },
      { id: 1566, name: "Volkmarsen" },
    ],
  },
  {
    state_id: 113,
    state_name: "Himachal Praddesh",
    cities: [
      { id: 1314, name: "Baddi" },
      { id: 1430, name: "Kangra" },
      { id: 1049, name: "Manali" },
      { id: 1369, name: "Nalagarh" },
      { id: 1234, name: "Parwanoo" },
      { id: 1412, name: "Sujanpur Tira" },
    ],
  },
  {
    state_id: 95,
    state_name: "Himachal Pradesh",
    cities: [
      { id: 1665, name: "Baddi" },
      { id: 526, name: "Dharamsala" },
      { id: 420, name: "Kullu" },
      { id: 415, name: "Mandi" },
      { id: 417, name: "Nahan" },
      { id: 1632, name: "Nurpur" },
      { id: 419, name: "Palampur" },
      { id: 1713, name: "Parwanoo" },
      { id: 414, name: "Shimla" },
      { id: 416, name: "Solan" },
      { id: 418, name: "Sundarnagar" },
      { id: 1542, name: "Una" },
    ],
  },
  {
    state_id: 213,
    state_name: "Hyogo",
    cities: [{ id: 1485, name: "Amagasaki" }],
  },
  {
    state_id: 144,
    state_name: "Île-de-france",
    cities: [
      { id: 1673, name: "Cergy" },
      { id: 1627, name: "Châtillon" },
      { id: 1520, name: "Courbevoie" },
      { id: 1294, name: "Poissy" },
      { id: 1790, name: "Rueil-malmaison" },
      { id: 1792, name: "Saint-ouen-sur-seine" },
    ],
  },
  {
    state_id: 173,
    state_name: "Illinois",
    cities: [
      { id: 1586, name: "Addison" },
      { id: 1702, name: "Alton" },
      { id: 1410, name: "Berwyn" },
      { id: 1497, name: "Cary" },
    ],
  },
  {
    state_id: 241,
    state_name: "Istanbul",
    cities: [{ id: 1564, name: "Istanbul" }],
  },
  {
    state_id: 210,
    state_name: "Jakarta",
    cities: [{ id: 1477, name: "Jakarta" }],
  },
  {
    state_id: 101,
    state_name: "Jammu and Kashmir",
    cities: [
      { id: 579, name: "Anantnag" },
      { id: 578, name: "Baramula" },
      { id: 1321, name: "Bishnah" },
      { id: 577, name: "Jammu" },
      { id: 1300, name: "Kathua" },
      { id: 581, name: "KathUrban Agglomeration" },
      { id: 1443, name: "Kishtwar" },
      { id: 1465, name: "Pulwama" },
      { id: 585, name: "Punch" },
      { id: 582, name: "Rajauri" },
      { id: 1622, name: "Samba" },
      { id: 580, name: "Sopore" },
      { id: 576, name: "Srinagar" },
      { id: 584, name: "Udhampur" },
    ],
  },
  {
    state_id: 302,
    state_name: "Jeonbuk",
    cities: [{ id: 1782, name: "Jeongeup-si" }],
  },
  {
    state_id: 87,
    state_name: "Jharkhand",
    cities: [
      { id: 63, name: "Adityapur" },
      { id: 60, name: "Bokaro Steel City" },
      { id: 71, name: "Chaibasa" },
      { id: 72, name: "Chatra" },
      { id: 76, name: "Chirkunda" },
      { id: 61, name: "Deoghar" },
      { id: 57, name: "Dhanbad" },
      { id: 74, name: "Dumka" },
      { id: 1389, name: "Garhwa" },
      { id: 65, name: "Giridih" },
      { id: 73, name: "Gumia" },
      { id: 64, name: "Hazaribag" },
      { id: 59, name: "Jamshedpur" },
      { id: 1534, name: "Jamtara" },
      { id: 67, name: "Jhumri Tilaiya" },
      { id: 82, name: "Lohardaga" },
      { id: 75, name: "Madhupur" },
      { id: 70, name: "Medininagar (Daltonganj)" },
      { id: 80, name: "Mihijam" },
      { id: 79, name: "Musabani" },
      { id: 77, name: "Pakaur" },
      { id: 81, name: "Patratu" },
      { id: 62, name: "Phusro" },
      { id: 66, name: "Ramgarh" },
      { id: 58, name: "Ranchi" },
      { id: 69, name: "Sahibganj" },
      { id: 68, name: "Saunda" },
      { id: 78, name: "Simdega" },
      { id: 83, name: "Tenu dam-cum-Kathhara" },
    ],
  },
  {
    state_id: 227,
    state_name: "Jiangsu",
    cities: [
      { id: 1597, name: "Changshu" },
      { id: 1661, name: "Changzhou" },
      { id: 1522, name: "Huaian" },
      { id: 1526, name: "Jiangyin" },
      { id: 1583, name: "Wuxi" },
    ],
  },
  {
    state_id: 212,
    state_name: "Kanagawa",
    cities: [
      { id: 1484, name: "Kawasaki" },
      { id: 1648, name: "Yokohama" },
    ],
  },
  {
    state_id: 176,
    state_name: "Kansai",
    cities: [{ id: 1428, name: "Osaka" }],
  },
  { state_id: 245, state_name: "Kansas", cities: [{ id: null, name: null }] },
  {
    state_id: 100,
    state_name: "Karnataka",
    cities: [
      { id: 666, name: "Adyar" },
      { id: 647, name: "Afzalpur" },
      { id: 609, name: "Arsikere" },
      { id: 616, name: "Athni" },
      { id: 1631, name: "Babaleshwar" },
      { id: 1449, name: "Badami" },
      { id: 1633, name: "Bagalkote" },
      { id: 590, name: "Ballari" },
      { id: 1634, name: "Basavakalyan" },
      { id: 588, name: "Belagavi" },
      { id: 1268, name: "Belgaum" },
      { id: 583, name: "Bengaluru" },
      { id: 1639, name: "Bidar" },
      { id: 1712, name: "Bijapur/ Vijayapura" },
      { id: 1640, name: "Chamarajanagar" },
      { id: 1643, name: "Channapatna" },
      { id: 1645, name: "Chikkaballapur" },
      { id: 600, name: "Chikkamagaluru" },
      { id: 1576, name: "Chitradurga" },
      { id: 589, name: "Davanagere" },
      { id: 1715, name: "Dharwad" },
      { id: 605, name: "Gokak" },
      { id: 1616, name: "Gulbarga/kalaburagi" },
      { id: 1641, name: "Gundlupete" },
      { id: 1483, name: "Hagaribommanahalli" },
      { id: 1644, name: "Harihar" },
      { id: 1646, name: "Hassan" },
      { id: 1579, name: "Haveri" },
      { id: 1647, name: "Hiriyur" },
      { id: 1270, name: "Hosapete" },
      { id: 1590, name: "Hoskote" },
      { id: 586, name: "Hubli-Dharwad" },
      { id: 1650, name: "Jamkhandi" },
      { id: 1727, name: "Kanakapura" },
      { id: 599, name: "Karwar" },
      { id: 596, name: "Kolar" },
      { id: 627, name: "Lakshmeshwar" },
      { id: 633, name: "Lingsugur" },
      { id: 648, name: "Maddur" },
      { id: 649, name: "Madhugiri" },
      { id: 636, name: "Madikeri" },
      { id: 653, name: "Magadi" },
      { id: 640, name: "Mahalingapura" },
      { id: 630, name: "Malavalli" },
      { id: 645, name: "Malur" },
      { id: 597, name: "Mandya" },
      { id: 587, name: "Mangaluru" },
      { id: 624, name: "Manvi" },
      { id: 652, name: "Mudabidri" },
      { id: 641, name: "Mudalagi" },
      { id: 642, name: "Muddebihal" },
      { id: 619, name: "Mudhol" },
      { id: 617, name: "Mulbagal" },
      { id: 661, name: "Mundargi" },
      { id: 591, name: "Mysore" },
      { id: 612, name: "Nanjangud" },
      { id: 629, name: "Nargund" },
      { id: 655, name: "Navalgund" },
      { id: 626, name: "Nelamangala" },
      { id: 1402, name: "Nipani" },
      { id: 643, name: "Pavagada" },
      { id: 663, name: "Piriyapatna" },
      { id: 614, name: "Puttur" },
      { id: 595, name: "Raayachuru" },
      { id: 606, name: "Rabkavi Banhatti" },
      { id: 1649, name: "Raichur" },
      { id: 603, name: "Ramanagaram" },
      { id: 628, name: "Ramdurg" },
      { id: 601, name: "Ranebennuru" },
      { id: 602, name: "Ranibennur" },
      { id: 594, name: "Robertson Pet" },
      { id: 660, name: "Ron" },
      { id: 662, name: "Sadalagi" },
      { id: 613, name: "Sagara" },
      { id: 658, name: "Sakaleshapura" },
      { id: 646, name: "Sanduru" },
      { id: 634, name: "Sankeshwara" },
      { id: 623, name: "Saundatti-Yellamma" },
      { id: 632, name: "Savanur" },
      { id: 638, name: "Sedam" },
      { id: 607, name: "Shahabad" },
      { id: 622, name: "Shahpur" },
      { id: 654, name: "Shiggaon" },
      { id: 639, name: "Shikaripur" },
      { id: 593, name: "Shivamogga" },
      { id: 656, name: "Shrirangapattana" },
      { id: 621, name: "Sidlaghatta" },
      { id: 657, name: "Sindagi" },
      { id: 644, name: "Sindhagi" },
      { id: 610, name: "Sindhnur" },
      { id: 615, name: "Sira" },
      { id: 608, name: "Sirsi" },
      { id: 620, name: "Siruguppa" },
      { id: 659, name: "Srinivaspur" },
      { id: 618, name: "Surapura" },
      { id: 637, name: "Talikota" },
      { id: 631, name: "Tarikere" },
      { id: 650, name: "Tekkalakote" },
      { id: 651, name: "Terdal" },
      { id: 611, name: "Tiptur" },
      { id: 592, name: "Tumkur" },
      { id: 598, name: "Udupi" },
      { id: 635, name: "Vijayapura" },
      { id: 625, name: "Wadi" },
      { id: 604, name: "Yadgir" },
    ],
  },
  {
    state_id: 260,
    state_name: "Kathmandu ",
    cities: [{ id: null, name: null }],
  },
  {
    state_id: 152,
    state_name: "Kent",
    cities: [
      { id: 1305, name: "Ashford" },
      { id: 1489, name: "Gillingham F.c." },
    ],
  },
  {
    state_id: 103,
    state_name: "Kerala",
    cities: [
      { id: 710, name: "Adoor" },
      { id: 675, name: "Alappuzha" },
      { id: 1310, name: "Aluva" },
      { id: 705, name: "Attingal" },
      { id: 1714, name: "Calicut" },
      { id: 693, name: "Chalakudy" },
      { id: 694, name: "Changanassery" },
      { id: 698, name: "Cherthala" },
      { id: 1332, name: "Chittarikkal" },
      { id: 707, name: "Chittur-Thathamangalam" },
      { id: 1255, name: "Ernakulam" },
      { id: 717, name: "Guruvayoor" },
      { id: 680, name: "Kanhangad" },
      { id: 1388, name: "Kanjirappally" },
      { id: 685, name: "Kannur" },
      { id: 687, name: "Kasaragod" },
      { id: 683, name: "Kayamkulam" },
      { id: 672, name: "Kochi" },
      { id: 706, name: "Kodungallur" },
      { id: 669, name: "Kollam" },
      { id: 1380, name: "Kottakkal" },
      { id: 688, name: "Kottayam" },
      { id: 681, name: "Koyilandy" },
      { id: 670, name: "Kozhikode" },
      { id: 689, name: "Kunnamkulam" },
      { id: 1348, name: "Mala" },
      { id: 676, name: "Malappuram" },
      { id: 700, name: "Mattannur" },
      { id: 711, name: "Mavelikkara" },
      { id: 713, name: "Mavoor" },
      { id: 709, name: "Muvattupuzha" },
      { id: 684, name: "Nedumangad" },
      { id: 682, name: "Neyyattinkara" },
      { id: 696, name: "Nilambur" },
      { id: 690, name: "Ottappalam" },
      { id: 715, name: "Palai" },
      { id: 674, name: "Palakkad" },
      { id: 719, name: "Panamattom" },
      { id: 716, name: "Panniyannur" },
      { id: 708, name: "Pappinisseri" },
      { id: 701, name: "Paravoor" },
      { id: 702, name: "Pathanamthitta" },
      { id: 704, name: "Peringathur" },
      { id: 697, name: "Perinthalmanna" },
      { id: 712, name: "Perumbavoor" },
      { id: 678, name: "Ponnani" },
      { id: 695, name: "Punalur" },
      { id: 718, name: "Puthuppally" },
      { id: 699, name: "Shoranur" },
      { id: 1413, name: "Sultan Bathery" },
      { id: 679, name: "Taliparamba" },
      { id: 691, name: "Thiruvalla" },
      { id: 671, name: "Thiruvananthapuram" },
      { id: 692, name: "Thodupuzha" },
      { id: 673, name: "Thrissur" },
      { id: 686, name: "Tirur" },
      { id: 714, name: "Vaikom" },
      { id: 703, name: "Varkala" },
      { id: 677, name: "Vatakara" },
    ],
  },
  {
    state_id: 286,
    state_name: "Kuala Lumpur",
    cities: [{ id: 1721, name: "Kuala Lumpur" }],
  },
  {
    state_id: 135,
    state_name: "Kyoto Prefecture",
    cities: [{ id: 1286, name: "Kyoto" }],
  },
  {
    state_id: 192,
    state_name: "Latina",
    cities: [{ id: 1450, name: "Aprilia" }],
  },
  { state_id: 271, state_name: "Lazio", cities: [{ id: 1674, name: "Rome" }] },
  {
    state_id: 194,
    state_name: "Leicestershire",
    cities: [{ id: 1453, name: "Loughborough" }],
  },
  {
    state_id: 195,
    state_name: "Leicestershire",
    cities: [{ id: null, name: null }],
  },
  {
    state_id: 269,
    state_name: "Leinster",
    cities: [{ id: 1669, name: "Dublin" }],
  },
  {
    state_id: 229,
    state_name: "Liaoning",
    cities: [{ id: 1528, name: "Yingkou" }],
  },
  {
    state_id: 156,
    state_name: "Lincolnshire",
    cities: [{ id: 1309, name: "Grantham" }],
  },
  { state_id: 268, state_name: "Lleida", cities: [{ id: null, name: null }] },
  {
    state_id: 254,
    state_name: "Lodi (lo)",
    cities: [{ id: 1613, name: "San Rocco" }],
  },
  {
    state_id: 146,
    state_name: "Lombardy(lombardia)",
    cities: [
      { id: 1694, name: "Cesana Brianza" },
      { id: 1602, name: "Milano" },
    ],
  },
  { state_id: 203, state_name: "London", cities: [{ id: null, name: null }] },
  {
    state_id: 178,
    state_name: "Louisiana",
    cities: [{ id: 1433, name: "Mandeville" }],
  },
  {
    state_id: 253,
    state_name: "Lower Austria",
    cities: [
      { id: 1740, name: "Leobersdorf" },
      { id: 1610, name: "Ternitz" },
    ],
  },
  {
    state_id: 211,
    state_name: "Lower Saxony",
    cities: [
      { id: 1743, name: "Aerzen" },
      { id: 1545, name: "Celle" },
      { id: 1481, name: "Zeven" },
    ],
  },
  {
    state_id: 277,
    state_name: "Luzhu",
    cities: [{ id: 1686, name: "Kaohsiung" }],
  },
  {
    state_id: 92,
    state_name: "Madhya Pradesh",
    cities: [
      { id: 322, name: "Alirajpur" },
      { id: 319, name: "Ashok Nagar" },
      { id: 317, name: "Balaghat" },
      { id: 1416, name: "Barnagar" },
      { id: 296, name: "Bhopal" },
      { id: 1423, name: "Burhanpur" },
      { id: 1426, name: "Chhatarpur" },
      { id: 1654, name: "Chhindwara" },
      { id: 1246, name: "Dewas" },
      { id: 1655, name: "Dhar" },
      { id: 1365, name: "Gadarwara" },
      { id: 308, name: "Ganjbasoda" },
      { id: 1239, name: "Ghatabillod" },
      { id: 1232, name: "Guna" },
      { id: 298, name: "Gwalior" },
      { id: 1658, name: "Harda" },
      { id: 294, name: "Indore" },
      { id: 312, name: "Itarsi" },
      { id: 297, name: "Jabalpur" },
      { id: 1387, name: "Katni" },
      { id: 1660, name: "Khargone" },
      { id: 339, name: "Lahar" },
      { id: 369, name: "Maharajpur" },
      { id: 351, name: "Mahidpur" },
      { id: 341, name: "Maihar" },
      { id: 346, name: "Malaj Khand" },
      { id: 363, name: "Manasa" },
      { id: 355, name: "Manawar" },
      { id: 336, name: "Mandideep" },
      { id: 324, name: "Mandla" },
      { id: 310, name: "Mandsaur" },
      { id: 362, name: "Mauganj" },
      { id: 316, name: "Mhow Cantonment" },
      { id: 374, name: "Mhowgaon" },
      { id: 304, name: "Morena" },
      { id: 370, name: "Multai" },
      { id: 347, name: "Mundi" },
      { id: 302, name: "Murwara (Katni)" },
      { id: 313, name: "Nagda" },
      { id: 365, name: "Nainpur" },
      { id: 376, name: "Narsinghgarh" },
      { id: 345, name: "Narsinghgarh" },
      { id: 311, name: "Neemuch" },
      { id: 349, name: "Nepanagar" },
      { id: 361, name: "Niwari" },
      { id: 334, name: "Nowgong" },
      { id: 367, name: "Nowrozabad (Khodargama)" },
      { id: 372, name: "Pachore" },
      { id: 371, name: "Pali" },
      { id: 356, name: "Panagar" },
      { id: 335, name: "Pandhurna" },
      { id: 327, name: "Panna" },
      { id: 350, name: "Pasan" },
      { id: 330, name: "Pipariya" },
      { id: 323, name: "Pithampur" },
      { id: 344, name: "Porsa" },
      { id: 364, name: "Prithvipur" },
      { id: 328, name: "Raghogarh-Vijaypur" },
      { id: 354, name: "Rahatgarh" },
      { id: 338, name: "Raisen" },
      { id: 360, name: "Rajgarh" },
      { id: 301, name: "Ratlam" },
      { id: 373, name: "Rau" },
      { id: 353, name: "Rehli" },
      { id: 306, name: "Rewa" },
      { id: 343, name: "Sabalgarh" },
      { id: 300, name: "Sagar" },
      { id: 340, name: "Sanawad" },
      { id: 348, name: "Sarangpur" },
      { id: 315, name: "Sarni" },
      { id: 303, name: "Satna" },
      { id: 359, name: "Sausar" },
      { id: 314, name: "Sehore" },
      { id: 329, name: "Sendhwa" },
      { id: 318, name: "Seoni" },
      { id: 352, name: "Seoni-Malwa" },
      { id: 321, name: "Shahdol" },
      { id: 326, name: "Shajapur" },
      { id: 368, name: "Shamgarh" },
      { id: 325, name: "Sheopur" },
      { id: 309, name: "Shivpuri" },
      { id: 333, name: "Shujalpur" },
      { id: 331, name: "Sidhi" },
      { id: 337, name: "Sihora" },
      { id: 305, name: "Singrauli" },
      { id: 332, name: "Sironj" },
      { id: 366, name: "Sohagpur" },
      { id: 1398, name: "Sonkatch" },
      { id: 357, name: "Tarana" },
      { id: 320, name: "Tikamgarh" },
      { id: 299, name: "Ujjain" },
      { id: 342, name: "Umaria" },
      { id: 307, name: "Vidisha" },
      { id: 375, name: "Vijaypur" },
      { id: 358, name: "Wara Seoni" },
    ],
  },
  {
    state_id: 116,
    state_name: "Maharashtra",
    cities: [
      { id: 1079, name: "Achalpur" },
      { id: 1073, name: "Ahmednagar" },
      { id: 1664, name: "Ahmedpur" },
      { id: 1663, name: "Akkalkot" },
      { id: 1068, name: "Akola" },
      { id: 1667, name: "Akole" },
      { id: 1086, name: "Akot" },
      { id: 1668, name: "Alibag" },
      { id: 1085, name: "Amalner" },
      { id: 1092, name: "Ambejogai" },
      { id: 1066, name: "Amravati" },
      { id: 1101, name: "Anjangaon" },
      { id: 1117, name: "Arvi" },
      { id: 1084, name: "Aurangabad" },
      { id: 1530, name: "Baramati" },
      { id: 1421, name: "Basmathnagar" },
      { id: 1591, name: "Beed" },
      { id: 1326, name: "Bhandara" },
      { id: 1065, name: "Bhiwandi" },
      { id: 1341, name: "Bhusawal" },
      { id: 1238, name: "Boisar" },
      { id: 1334, name: "Buldhana" },
      { id: 1424, name: "Chalisgaon" },
      { id: 1425, name: "Chandrapur" },
      { id: 1329, name: "Chikhli" },
      { id: 1330, name: "Chiplun" },
      { id: 1628, name: "Daryapur" },
      { id: 1587, name: "Devarwadi" },
      { id: 1072, name: "Dhule" },
      { id: 1735, name: "Dombivli" },
      { id: 1463, name: "Gadchiroli" },
      { id: 1335, name: "Gangakhed" },
      { id: 1333, name: "Gondia" },
      { id: 1374, name: "Hinganghat" },
      { id: 1074, name: "Ichalkaranji" },
      { id: 1375, name: "Jalgaon" },
      { id: 1376, name: "Jalna" },
      { id: 1061, name: "Kalyan-Dombivali" },
      { id: 1235, name: "Karad" },
      { id: 1142, name: "Karjat" },
      { id: 1487, name: "Khed" },
      { id: 1247, name: "Khopoli" },
      { id: 1223, name: "Kolhapur" },
      { id: 1349, name: "Lasalgaon" },
      { id: 1071, name: "Latur" },
      { id: 1174, name: "Loha" },
      { id: 1161, name: "Lonar" },
      { id: 1100, name: "Lonavla" },
      { id: 1160, name: "Mahad" },
      { id: 1069, name: "Malegaon" },
      { id: 1098, name: "Malkapur" },
      { id: 1168, name: "Mangalvedhe" },
      { id: 1145, name: "Mangrulpir" },
      { id: 1115, name: "Manjlegaon" },
      { id: 1091, name: "Manmad" },
      { id: 1141, name: "Manwath" },
      { id: 1124, name: "Mehkar" },
      { id: 1172, name: "Mhaswad" },
      { id: 1064, name: "Mira-Bhayandar" },
      { id: 1134, name: "Morshi" },
      { id: 1155, name: "Mukhed" },
      { id: 1165, name: "Mul" },
      { id: 1056, name: "Mumbai" },
      { id: 1123, name: "Murtijapur" },
      { id: 1059, name: "Nagpur" },
      { id: 1067, name: "Nanded-Waghala" },
      { id: 1173, name: "Nandgaon" },
      { id: 1118, name: "Nandura" },
      { id: 1080, name: "Nandurbar" },
      { id: 1169, name: "Narkhed" },
      { id: 1060, name: "Nashik" },
      { id: 1221, name: "Navi Mumbai" },
      { id: 1132, name: "Nawapur" },
      { id: 1127, name: "Nilanga" },
      { id: 1078, name: "Osmanabad" },
      { id: 1106, name: "Ozar" },
      { id: 1112, name: "Pachora" },
      { id: 1129, name: "Paithan" },
      { id: 1104, name: "Palghar" },
      { id: 1154, name: "Pandharkaoda" },
      { id: 1087, name: "Pandharpur" },
      { id: 1076, name: "Panvel" },
      { id: 1075, name: "Parbhani" },
      { id: 1089, name: "Parli" },
      { id: 1144, name: "Partur" },
      { id: 1162, name: "Pathardi" },
      { id: 1137, name: "Pathri" },
      { id: 1171, name: "Patur" },
      { id: 1164, name: "Pauni" },
      { id: 1143, name: "Pen" },
      { id: 1107, name: "Phaltan" },
      { id: 1249, name: "Pimpri-Chinchwad" },
      { id: 1126, name: "Pulgaon" },
      { id: 1057, name: "Pune" },
      { id: 1135, name: "Purna" },
      { id: 1095, name: "Pusad" },
      { id: 1133, name: "Rahuri" },
      { id: 1227, name: "Raigad" },
      { id: 1157, name: "Rajura" },
      { id: 1163, name: "Ramtek" },
      { id: 1093, name: "Ratnagiri" },
      { id: 1156, name: "Raver" },
      { id: 1147, name: "Risod" },
      { id: 1121, name: "Sailu" },
      { id: 1096, name: "Sangamner" },
      { id: 1070, name: "Sangli" },
      { id: 1146, name: "Sangole" },
      { id: 1148, name: "Sasvad" },
      { id: 1136, name: "Satana" },
      { id: 1081, name: "Satara" },
      { id: 1150, name: "Savner" },
      { id: 1166, name: "Sawantwadi" },
      { id: 1109, name: "Shahade" },
      { id: 1105, name: "Shegaon" },
      { id: 1170, name: "Shendurjana" },
      { id: 1151, name: "Shirdi" },
      { id: 1097, name: "Shirpur-Warwade" },
      { id: 1149, name: "Shirur" },
      { id: 1153, name: "Shrigonda" },
      { id: 1088, name: "Shrirampur" },
      { id: 1116, name: "Sillod" },
      { id: 1139, name: "Sinnar" },
      { id: 1063, name: "Solapur" },
      { id: 1167, name: "Soyagaon" },
      { id: 1103, name: "Talegaon Dabhade" },
      { id: 1152, name: "Talode" },
      { id: 1122, name: "Tasgaon" },
      { id: 1058, name: "Thane" },
      { id: 1158, name: "Tirora" },
      { id: 1131, name: "Tuljapur" },
      { id: 1114, name: "Tumsar" },
      { id: 1138, name: "Uchgaon" },
      { id: 1083, name: "Udgir" },
      { id: 1750, name: "Ulhasnagar" },
      { id: 1128, name: "Umarga" },
      { id: 1111, name: "Umarkhed" },
      { id: 1102, name: "Umred" },
      { id: 1140, name: "Uran" },
      { id: 1094, name: "Uran Islampur" },
      { id: 1159, name: "Vadgaon Kasba" },
      { id: 1119, name: "Vaijapur" },
      { id: 1062, name: "Vasai-Virar" },
      { id: 1110, name: "Vita" },
      { id: 1120, name: "Wadgaon Road" },
      { id: 1130, name: "Wai" },
      { id: 1099, name: "Wani" },
      { id: 1082, name: "Wardha" },
      { id: 1113, name: "Warora" },
      { id: 1175, name: "Warud" },
      { id: 1090, name: "Washim" },
      { id: 1077, name: "Yavatmal" },
      { id: 1125, name: "Yawal" },
      { id: 1108, name: "Yevla" },
    ],
  },
  {
    state_id: 102,
    state_name: "Manipur",
    cities: [
      { id: 665, name: "Imphal" },
      { id: 667, name: "Lilong" },
      { id: 668, name: "Mayang Imphal" },
      { id: 664, name: "Thoubal" },
    ],
  },
  {
    state_id: 168,
    state_name: "Marche",
    cities: [{ id: 1383, name: "Borgo Santa Maria" }],
  },
  {
    state_id: 259,
    state_name: "Massachusetts",
    cities: [
      { id: 1629, name: "Burlington" },
      { id: 1642, name: "Greenfield" },
    ],
  },
  {
    state_id: 185,
    state_name: "Mazowieckie / Masovian Voivodeship",
    cities: [{ id: 1439, name: "Warsaw" }],
  },
  {
    state_id: 112,
    state_name: "Meghalaya",
    cities: [
      { id: 1050, name: "Nongstoin" },
      { id: 1044, name: "Shillong" },
      { id: 1047, name: "Tura" },
    ],
  },
  {
    state_id: 214,
    state_name: "Michigan",
    cities: [
      { id: 1491, name: "Portage" },
      { id: 1505, name: "Warren" },
    ],
  },
  {
    state_id: 124,
    state_name: "Milano",
    cities: [
      { id: 1500, name: "Binasco" },
      { id: 1264, name: "Milan" },
      { id: 1273, name: "Nerviano" },
    ],
  },
  {
    state_id: 201,
    state_name: "Minnesota",
    cities: [
      { id: 1466, name: "Mankato" },
      { id: 1518, name: "Shakopee" },
    ],
  },
  {
    state_id: 297,
    state_name: "Mississippi",
    cities: [{ id: 1766, name: "Hattiesburg" }],
  },
  {
    state_id: 158,
    state_name: "Missouri",
    cities: [{ id: 1318, name: "St. Louis" }],
  },
  {
    state_id: 90,
    state_name: "Mizoram",
    cities: [
      { id: 91, name: "Aizawl" },
      { id: 92, name: "Lunglei" },
      { id: 93, name: "Saiha" },
    ],
  },
  {
    state_id: 193,
    state_name: "Monza And Brianza",
    cities: [{ id: 1478, name: "Biassono" }],
  },
  {
    state_id: 187,
    state_name: "Monza And Brianza",
    cities: [
      { id: 1452, name: "Arcore" },
      { id: 1442, name: "Bellusco" },
      { id: 1785, name: "Villasanta" },
    ],
  },
  {
    state_id: 303,
    state_name: "Moravian-silesian",
    cities: [{ id: 1789, name: "Dolní Benešov" }],
  },
  {
    state_id: 154,
    state_name: "Moscow Oblast",
    cities: [
      { id: 1468, name: "Balashikha" },
      { id: 1307, name: "Moscow" },
    ],
  },
  {
    state_id: 238,
    state_name: "Mpumalanga",
    cities: [{ id: 1561, name: "Middelburg" }],
  },
  {
    state_id: 170,
    state_name: "Muscat",
    cities: [{ id: 1385, name: "Muscat" }],
  },
  {
    state_id: 91,
    state_name: "Nagaland",
    cities: [
      { id: 94, name: "Dimapur" },
      { id: 95, name: "Kohima" },
      { id: 98, name: "Mokokchung" },
      { id: 97, name: "Tuensang" },
      { id: 99, name: "Wokha" },
      { id: 96, name: "Zunheboto" },
    ],
  },
  { state_id: 242, state_name: "Nagano", cities: [{ id: 1571, name: "Ueda" }] },
  {
    state_id: 207,
    state_name: "Negeri Sembilan",
    cities: [{ id: 1473, name: "Seremban" }],
  },
  {
    state_id: 216,
    state_name: "New Jersey",
    cities: [
      { id: 1767, name: "Asbury" },
      { id: 1498, name: "Jersey" },
    ],
  },
  {
    state_id: 215,
    state_name: "New South Wales",
    cities: [
      { id: 1565, name: "Parramatta" },
      { id: 1494, name: "Sydney" },
    ],
  },
  {
    state_id: 265,
    state_name: "New Taipei",
    cities: [{ id: 1653, name: "New Taipei" }],
  },
  {
    state_id: 181,
    state_name: "New York",
    cities: [
      { id: 1585, name: "Batavia" },
      { id: 1779, name: "Islandia" },
      { id: 1725, name: "Niskayuna" },
      { id: 1435, name: "Rochester" },
    ],
  },
  {
    state_id: 202,
    state_name: "Norfolk",
    cities: [{ id: 1467, name: "Norwich" }],
  },
  {
    state_id: 222,
    state_name: "Norte (north Of Portugal)",
    cities: [{ id: 1515, name: "Santa Maria Da Feira" }],
  },
  {
    state_id: 164,
    state_name: "North Carolina",
    cities: [{ id: 1354, name: "Kings Mountain" }],
  },
  {
    state_id: 274,
    state_name: "North Gyeongsang",
    cities: [{ id: 1681, name: "Gumi-si" }],
  },
  {
    state_id: 129,
    state_name: "North Rhine-westphalia",
    cities: [
      { id: 1569, name: "Beckum" },
      { id: 1537, name: "Bocholt" },
      { id: 1506, name: "Bottrop" },
      { id: 1770, name: "Brilon" },
      { id: 1280, name: "Cologne" },
      { id: 1317, name: "Dortmund" },
      { id: 1474, name: "Herne" },
      { id: 1617, name: "Kirchhundem" },
      { id: 1596, name: "Menden" },
      { id: 1488, name: "Mülheim An Der Ruhr" },
      { id: 1567, name: "Neuenrade" },
      { id: 1514, name: "Rheine" },
      { id: 1524, name: "Schloß Holte-stukenbrock" },
      { id: 1556, name: "Schwelm" },
      { id: 1677, name: "Solingen" },
      { id: 1525, name: "Tönisvorst" },
      { id: 1440, name: "Werdohl" },
      { id: 1619, name: "Wuppertal" },
    ],
  },
  {
    state_id: 252,
    state_name: "North Yorkshire",
    cities: [{ id: 1608, name: "Skelton" }],
  },
  {
    state_id: 98,
    state_name: "Odisha",
    cities: [
      { id: 1222, name: "Angul" },
      { id: 533, name: "Balangir" },
      { id: 1420, name: "Balasore" },
      { id: 529, name: "Baleshwar Town" },
      { id: 538, name: "Barbil" },
      { id: 534, name: "Bargarh" },
      { id: 530, name: "Baripada Town" },
      { id: 531, name: "Bhadrak" },
      { id: 536, name: "Bhawanipatna" },
      { id: 522, name: "Bhubaneswar" },
      { id: 1540, name: "Binka" },
      { id: 1672, name: "Brahmapur / Berhampur " },
      { id: 542, name: "Byasanagar" },
      { id: 524, name: "Cuttack" },
      { id: 537, name: "Dhenkanal" },
      { id: 1755, name: "Jagatsinghpur" },
      { id: 1760, name: "Jajpur" },
      { id: 543, name: "Jatani" },
      { id: 1716, name: "Jeypore" },
      { id: 532, name: "Jharsuguda" },
      { id: 1240, name: "Kalunga" },
      { id: 544, name: "Kendrapara" },
      { id: 539, name: "Kendujhar" },
      { id: 1404, name: "Khordha" },
      { id: 1759, name: "Kujang" },
      { id: 554, name: "Malkangiri" },
      { id: 553, name: "Nabarangapur" },
      { id: 1508, name: "Nayagarh" },
      { id: 535, name: "Paradip" },
      { id: 546, name: "Parlakhemundi" },
      { id: 549, name: "Pattamundai" },
      { id: 550, name: "Phulabani" },
      { id: 528, name: "Puri" },
      { id: 555, name: "Rairangpur" },
      { id: 545, name: "Rajagangapur" },
      { id: 1403, name: "Rasulgarh" },
      { id: 525, name: "Raurkela" },
      { id: 541, name: "Rayagada" },
      { id: 1778, name: "Rourkela" },
      { id: 527, name: "Sambalpur" },
      { id: 552, name: "Soro" },
      { id: 540, name: "Sunabeda" },
      { id: 548, name: "Sundargarh" },
      { id: 547, name: "Talcher" },
      { id: 556, name: "Tarbha" },
      { id: 551, name: "Titlagarh" },
    ],
  },
  {
    state_id: 148,
    state_name: "Ohio",
    cities: [
      { id: 1786, name: "Cleveland" },
      { id: 1299, name: "Maumee" },
      { id: 1791, name: "Solon" },
      { id: 1357, name: "Toledo" },
    ],
  },
  {
    state_id: 204,
    state_name: "Oklahoma",
    cities: [{ id: 1469, name: "Tulsa" }],
  },
  {
    state_id: 150,
    state_name: "Ontario",
    cities: [
      { id: 1480, name: "Mississauga" },
      { id: 1302, name: "Richmond Hill" },
      { id: 1353, name: "Sarnia" },
    ],
  },
  {
    state_id: 231,
    state_name: "Opole Voivodeship",
    cities: [{ id: 1536, name: "Kluczbork" }],
  },
  {
    state_id: 196,
    state_name: "Padova (pd)",
    cities: [{ id: 1454, name: "Limena" }],
  },
  {
    state_id: 134,
    state_name: "Pennsylvania",
    cities: [
      { id: 1620, name: "Annville" },
      { id: 1607, name: "Hatfield" },
      { id: 1431, name: "Ivyland" },
      { id: 1285, name: "Lebanon" },
      { id: 1624, name: "Moon Township" },
      { id: 1730, name: "Southampton" },
    ],
  },
  {
    state_id: 122,
    state_name: "Pennsylvania (pa)",
    cities: [
      { id: 1604, name: "Bethlehem" },
      { id: 1261, name: "Lansdale" },
      { id: 1513, name: "Saxton" },
    ],
  },
  {
    state_id: 295,
    state_name: "Province Of Pavia",
    cities: [{ id: 1748, name: "Stradella" }],
  },
  {
    state_id: 106,
    state_name: "Puducherry",
    cities: [
      { id: 724, name: "Karaikal" },
      { id: 726, name: "Mahe" },
      { id: 722, name: "Pondicherry" },
      { id: 725, name: "Yanam" },
    ],
  },
  {
    state_id: 85,
    state_name: "Punjab",
    cities: [
      { id: 3, name: "Amritsar" },
      { id: 1678, name: "Bareta" },
      { id: 12, name: "Barnala" },
      { id: 8, name: "Batala" },
      { id: 6, name: "Bathinda" },
      { id: 1733, name: "Dera Bassi" },
      { id: 32, name: "Dhuri" },
      { id: 21, name: "Faridkot" },
      { id: 22, name: "Fazilka" },
      { id: 15, name: "Firozpur" },
      { id: 36, name: "Firozpur Cantt." },
      { id: 25, name: "Gobindgarh" },
      { id: 27, name: "Gurdaspur" },
      { id: 9, name: "Hoshiarpur" },
      { id: 34, name: "Jagraon" },
      { id: 5, name: "Jalandhar" },
      { id: 38, name: "Jalandhar Cantt." },
      { id: 1377, name: "Jandiala Guru" },
      { id: 16, name: "Kapurthala" },
      { id: 13, name: "Khanna" },
      { id: 26, name: "Kharar" },
      { id: 19, name: "Kot Kapura" },
      { id: 47, name: "Longowal" },
      { id: 2, name: "Ludhiana" },
      { id: 1344, name: "Makhu" },
      { id: 11, name: "Malerkotla" },
      { id: 29, name: "Malout" },
      { id: 28, name: "Mansa" },
      { id: 10, name: "Moga" },
      { id: 14, name: "Mohali" },
      { id: 48, name: "Morinda, India" },
      { id: 54, name: "Mukerian" },
      { id: 20, name: "Muktsar" },
      { id: 31, name: "Nabha" },
      { id: 43, name: "Nakodar" },
      { id: 44, name: "Nangal" },
      { id: 40, name: "Nawanshahr" },
      { id: 1581, name: "Naya Nangal" },
      { id: 7, name: "Pathankot" },
      { id: 4, name: "Patiala" },
      { id: 45, name: "Patti" },
      { id: 51, name: "Pattran" },
      { id: 17, name: "Phagwara" },
      { id: 50, name: "Phillaur" },
      { id: 53, name: "Qadian" },
      { id: 46, name: "Raikot" },
      { id: 23, name: "Rajpura" },
      { id: 41, name: "Rampura Phul" },
      { id: 37, name: "Rupnagar" },
      { id: 39, name: "Samana" },
      { id: 24, name: "Sangrur" },
      { id: 1408, name: "Shahkot" },
      { id: 35, name: "Sirhind Fatehgarh Sahib" },
      { id: 52, name: "Sujanpur" },
      { id: 33, name: "Sunam" },
      { id: 55, name: "Talwara" },
      { id: 30, name: "Tarn Taran" },
      { id: 49, name: "Urmar Tanda" },
      { id: 42, name: "Zira" },
      { id: 18, name: "Zirakpur" },
    ],
  },
  {
    state_id: 139,
    state_name: "Queensland",
    cities: [{ id: 1290, name: "Brisbane" }],
  },
  {
    state_id: 96,
    state_name: "Rajasthan",
    cities: [
      { id: 424, name: "Ajmer" },
      { id: 427, name: "Alwar" },
      { id: 1394, name: "Atru" },
      { id: 1253, name: "Balotra" },
      { id: 1315, name: "Bansur" },
      { id: 1262, name: "Banswara" },
      { id: 1319, name: "Baran" },
      { id: 430, name: "Barmer" },
      { id: 1396, name: "Bayana" },
      { id: 1395, name: "Beawar" },
      { id: 1543, name: "Behror" },
      { id: 428, name: "Bharatpur" },
      { id: 426, name: "Bhilwara" },
      { id: 1224, name: "Bhiwadi" },
      { id: 1225, name: "Bhiwali" },
      { id: 423, name: "Bikaner" },
      { id: 1323, name: "Bilara" },
      { id: 1531, name: "Chittorgarh" },
      { id: 1427, name: "Chomu" },
      { id: 1338, name: "Dausa" },
      { id: 1269, name: "Dholpur" },
      { id: 1676, name: "Dungarpur" },
      { id: 1368, name: "Hanumangarh" },
      { id: 1370, name: "Hindaun" },
      { id: 421, name: "Jaipur" },
      { id: 1544, name: "Jaisalmer" },
      { id: 1575, name: "Jhalawar" },
      { id: 1325, name: "Jhunjhunu" },
      { id: 422, name: "Jodhpur" },
      { id: 1265, name: "Kapasan" },
      { id: 1229, name: "Kota" },
      { id: 1313, name: "Kotputli" },
      { id: 445, name: "Lachhmangarh" },
      { id: 438, name: "Ladnu" },
      { id: 467, name: "Lakheri" },
      { id: 459, name: "Lalsot" },
      { id: 469, name: "Losal" },
      { id: 1342, name: "Mahwa" },
      { id: 436, name: "Makrana" },
      { id: 477, name: "Malpura" },
      { id: 496, name: "Mandalgarh" },
      { id: 494, name: "Mandawa" },
      { id: 493, name: "Mangrol" },
      { id: 453, name: "Merta City" },
      { id: 490, name: "Mount Abu" },
      { id: 478, name: "Nadbai" },
      { id: 480, name: "Nagar" },
      { id: 434, name: "Nagaur" },
      { id: 447, name: "Nasirabad" },
      { id: 449, name: "Nathdwara" },
      { id: 1401, name: "Nawalgarh" },
      { id: 454, name: "Neem-Ka-Thana" },
      { id: 443, name: "Nimbahera" },
      { id: 450, name: "Nohar" },
      { id: 441, name: "Nokha" },
      { id: 429, name: "Pali" },
      { id: 448, name: "Phalodi" },
      { id: 492, name: "Phulera" },
      { id: 451, name: "Pilani" },
      { id: 460, name: "Pilibanga" },
      { id: 495, name: "Pindwara" },
      { id: 461, name: "Pipar City" },
      { id: 491, name: "Prantij" },
      { id: 456, name: "Pratapgarh" },
      { id: 476, name: "Raisinghnagar" },
      { id: 472, name: "Rajakhera" },
      { id: 487, name: "Rajaldesar" },
      { id: 481, name: "Rajgarh (Alwar)" },
      { id: 446, name: "Rajgarh (Churu)" },
      { id: 444, name: "Rajsamand" },
      { id: 466, name: "Ramganj Mandi" },
      { id: 471, name: "Ramngarh" },
      { id: 440, name: "Ratangarh" },
      { id: 458, name: "Rawatbhata" },
      { id: 473, name: "Rawatsar" },
      { id: 486, name: "Reengus" },
      { id: 482, name: "Sadri" },
      { id: 433, name: "Sadulpur" },
      { id: 488, name: "Sadulshahar" },
      { id: 465, name: "Sagwara" },
      { id: 489, name: "Sambhar" },
      { id: 479, name: "Sanchore" },
      { id: 457, name: "Sangaria" },
      { id: 439, name: "Sardarshahar" },
      { id: 435, name: "Sawai Madhopur" },
      { id: 474, name: "Shahpura" },
      { id: 475, name: "Shahpura" },
      { id: 483, name: "Sheoganj" },
      { id: 431, name: "Sikar" },
      { id: 455, name: "Sirohi" },
      { id: 452, name: "Sojat" },
      { id: 1411, name: "Sri Ganganagar" },
      { id: 470, name: "Sri Madhopur" },
      { id: 437, name: "Sujangarh" },
      { id: 464, name: "Sumerpur" },
      { id: 442, name: "Suratgarh" },
      { id: 498, name: "Takhatgarh" },
      { id: 462, name: "Taranagar" },
      { id: 485, name: "Todabhim" },
      { id: 484, name: "Todaraisingh" },
      { id: 432, name: "Tonk" },
      { id: 425, name: "Udaipur" },
      { id: 468, name: "Udaipurwati" },
      { id: 463, name: "Vijainagar, Ajmer" },
    ],
  },
  {
    state_id: 267,
    state_name: "Rende",
    cities: [{ id: 1657, name: "Tainan" }],
  },
  {
    state_id: 218,
    state_name: "Rhineland-palatinate",
    cities: [
      { id: 1729, name: "Daun" },
      { id: 1724, name: "Weilerbach" },
      { id: 1501, name: "Zweibrücken" },
    ],
  },
  { state_id: 182, state_name: "Rieti", cities: [{ id: null, name: null }] },
  {
    state_id: 180,
    state_name: "Rochester",
    cities: [{ id: null, name: null }],
  },
  {
    state_id: 246,
    state_name: "Rovigo",
    cities: [{ id: 1595, name: "Lendinara" }],
  },
  {
    state_id: 209,
    state_name: "Saarland",
    cities: [
      { id: 1476, name: "Saarbrücken" },
      { id: 1495, name: "Surendranagar" },
    ],
  },
  {
    state_id: 291,
    state_name: "Salzburg",
    cities: [{ id: 1739, name: "Salzburg" }],
  },
  {
    state_id: 301,
    state_name: "Samut Prakan",
    cities: [{ id: null, name: null }],
  },
  {
    state_id: 130,
    state_name: "Schleswig-holstein",
    cities: [
      { id: 1781, name: "Bad Oldesloe" },
      { id: 1281, name: "Flensburg" },
      { id: 1697, name: "Lübeck" },
    ],
  },
  {
    state_id: 248,
    state_name: "Selangor",
    cities: [
      { id: 1662, name: "Kajang" },
      { id: 1600, name: "Subang Jaya" },
    ],
  },
  {
    state_id: 143,
    state_name: "Shandong",
    cities: [{ id: 1293, name: "Zouping" }],
  },
  {
    state_id: 257,
    state_name: "Shanghai",
    cities: [{ id: 1618, name: "Shanghai" }],
  },
  {
    state_id: 230,
    state_name: "Sharjah",
    cities: [{ id: 1535, name: "Sharjah" }],
  },
  {
    state_id: 287,
    state_name: "Sichuan",
    cities: [{ id: 1722, name: "Chengdu" }],
  },
  {
    state_id: 235,
    state_name: "Sikkim",
    cities: [{ id: 1549, name: "Singtam" }],
  },
  {
    state_id: 153,
    state_name: "Småland",
    cities: [{ id: 1306, name: "Jonkoping" }],
  },
  {
    state_id: 273,
    state_name: "Songbei",
    cities: [{ id: 1680, name: "Harbin" }],
  },
  {
    state_id: 289,
    state_name: "South Australia",
    cities: [{ id: 1734, name: "Adelaide" }],
  },
  {
    state_id: 228,
    state_name: "South Carolina",
    cities: [
      { id: 1523, name: "Rock Hill" },
      { id: 1611, name: "Spartanburg" },
    ],
  },
  {
    state_id: 258,
    state_name: "Southern Finland",
    cities: [{ id: 1621, name: "Lahti" }],
  },
  {
    state_id: 127,
    state_name: "South Gyeongsang",
    cities: [
      { id: 1277, name: "Hamyang-gun" },
      { id: 1371, name: "Ulsan" },
    ],
  },
  {
    state_id: 126,
    state_name: "South Holland",
    cities: [
      { id: 1777, name: "Dordrecht" },
      { id: 1731, name: "Pijnacker" },
      { id: 1275, name: "Ridderkerk" },
      { id: 1382, name: "Schiedam" },
    ],
  },
  {
    state_id: 247,
    state_name: "South Moravian Region",
    cities: [{ id: 1598, name: "Veselí Nad Moravou" }],
  },
  {
    state_id: 220,
    state_name: "South Yorkshire",
    cities: [{ id: 1504, name: "Rotherham" }],
  },
  {
    state_id: 198,
    state_name: "Staffordshire",
    cities: [{ id: 1458, name: "Stoke-on-trent" }],
  },
  {
    state_id: 251,
    state_name: "Stockholm",
    cities: [{ id: 1605, name: "Stockholm" }],
  },
  {
    state_id: 266,
    state_name: "Styria",
    cities: [{ id: 1656, name: "Gleisdorf" }],
  },
  {
    state_id: 138,
    state_name: "Surrey",
    cities: [{ id: 1289, name: "Camberley" }],
  },
  {
    state_id: 157,
    state_name: "Swansea",
    cities: [{ id: 1312, name: "Swansea City" }],
  },
  {
    state_id: 186,
    state_name: "Taiwan",
    cities: [{ id: 1441, name: "Tainan" }],
  },
  {
    state_id: 89,
    state_name: "Tamil Nadu",
    cities: [
      { id: 127, name: "Arakkonam" },
      { id: 1397, name: "Ariyalur" },
      { id: 125, name: "Aruppukkottai" },
      { id: 1675, name: "Attur" },
      { id: 100, name: "Chennai" },
      { id: 101, name: "Coimbatore" },
      { id: 1391, name: "Cuddalore" },
      { id: 1336, name: "Cumbum" },
      { id: 1271, name: "Dharmapuri" },
      { id: 1367, name: "Dindigul" },
      { id: 112, name: "Erode" },
      { id: 141, name: "Gobichettipalayam" },
      { id: 1457, name: "Gummidipoondi" },
      { id: 1254, name: "Hosur" },
      { id: 111, name: "Kancheepuram" },
      { id: 1379, name: "Kangayampalayam" },
      { id: 1464, name: "Kanniyakumari" },
      { id: 132, name: "Karur" },
      { id: 192, name: "Lalgudi" },
      { id: 102, name: "Madurai" },
      { id: 186, name: "Manachanallur" },
      { id: 1400, name: "Manapparai" },
      { id: 1414, name: "Mannargudi" },
      { id: 119, name: "Nagapattinam" },
      { id: 107, name: "Nagercoil" },
      { id: 203, name: "Namagiripettai" },
      { id: 145, name: "Namakkal" },
      { id: 151, name: "Nandivaram-Guduvancheri" },
      { id: 165, name: "Nanjikottai" },
      { id: 1356, name: "Narasimhanaickenpalayam" },
      { id: 193, name: "Natham" },
      { id: 147, name: "Nellikuppam" },
      { id: 117, name: "Neyveli (TS)" },
      { id: 173, name: "Oddanchatram" },
      { id: 199, name: "O' Valley" },
      { id: 198, name: "Pacode" },
      { id: 211, name: "Padmanabhapuram" },
      { id: 134, name: "Palani" },
      { id: 174, name: "Palladam" },
      { id: 190, name: "Pallapatti" },
      { id: 207, name: "Pallikonda" },
      { id: 187, name: "Panagudi" },
      { id: 144, name: "Panruti" },
      { id: 124, name: "Paramakudi" },
      { id: 205, name: "Parangipettai" },
      { id: 137, name: "Pattukkottai" },
      { id: 159, name: "Perambalur" },
      { id: 204, name: "Peravurani" },
      { id: 152, name: "Periyakulam" },
      { id: 167, name: "Periyasemur" },
      { id: 153, name: "Pernampattu" },
      { id: 195, name: "P.N.Patti" },
      { id: 116, name: "Pollachi" },
      { id: 185, name: "Polur" },
      { id: 191, name: "Ponneri" },
      { id: 1407, name: "Puducherry" },
      { id: 118, name: "Pudukkottai" },
      { id: 206, name: "Pudupattinam" },
      { id: 163, name: "Puliyankudi" },
      { id: 209, name: "Punjaipugalur" },
      { id: 114, name: "Rajapalayam" },
      { id: 139, name: "Ramanathapuram" },
      { id: 158, name: "Rameshwaram" },
      { id: 108, name: "Ranipet" },
      { id: 149, name: "Rasipuram" },
      { id: 105, name: "Salem" },
      { id: 136, name: "Sankarankovil" },
      { id: 179, name: "Sankari" },
      { id: 162, name: "Sathyamangalam" },
      { id: 169, name: "Sattur" },
      { id: 180, name: "Shenkottai" },
      { id: 201, name: "Sholavandan" },
      { id: 182, name: "Sholingur" },
      { id: 1784, name: "Singaperumal Koil" },
      { id: 166, name: "Sirkali" },
      { id: 155, name: "Sivaganga" },
      { id: 208, name: "Sivagiri" },
      { id: 115, name: "Sivakasi" },
      { id: 1231, name: "Sriperumbudur" },
      { id: 129, name: "Srivilliputhur" },
      { id: 178, name: "Surandai" },
      { id: 200, name: "Suriyampalayam" },
      { id: 135, name: "Tenkasi" },
      { id: 202, name: "Thammampatti" },
      { id: 109, name: "Thanjavur" },
      { id: 171, name: "Tharamangalam" },
      { id: 196, name: "Tharangambadi" },
      { id: 123, name: "Theni Allinagaram" },
      { id: 1415, name: "Thenkarai" },
      { id: 146, name: "Thirumangalam" },
      { id: 210, name: "Thirupuvanam" },
      { id: 189, name: "Thiruthuraipoondi" },
      { id: 143, name: "Thiruvallur" },
      { id: 142, name: "Thiruvarur" },
      { id: 1555, name: "Thoothukudi" },
      { id: 164, name: "Thuraiyur" },
      { id: 130, name: "Tindivanam" },
      { id: 168, name: "Tiruchendur" },
      { id: 121, name: "Tiruchengode" },
      { id: 103, name: "Tiruchirappalli" },
      { id: 175, name: "Tirukalukundram" },
      { id: 172, name: "Tirukkoyilur" },
      { id: 104, name: "Tirunelveli" },
      { id: 138, name: "Tirupathur" },
      { id: 183, name: "Tirupathur" },
      { id: 106, name: "Tiruppur" },
      { id: 150, name: "Tiruttani" },
      { id: 113, name: "Tiruvannamalai" },
      { id: 157, name: "Tiruvethipuram" },
      { id: 197, name: "Tittakudi" },
      { id: 126, name: "Udhagamandalam" },
      { id: 140, name: "Udumalaipettai" },
      { id: 194, name: "Unnamalaikadai" },
      { id: 160, name: "Usilampatti" },
      { id: 177, name: "Uthamapalayam" },
      { id: 188, name: "Uthiramerur" },
      { id: 176, name: "Vadakkuvalliyur" },
      { id: 156, name: "Vadalur" },
      { id: 181, name: "Vadipatti" },
      { id: 133, name: "Valparai" },
      { id: 170, name: "Vandavasi" },
      { id: 122, name: "Vaniyambadi" },
      { id: 1327, name: "Vattalagundu/batlagundu" },
      { id: 161, name: "Vedaranyam" },
      { id: 154, name: "Vellakoil" },
      { id: 110, name: "Vellore" },
      { id: 1592, name: "Veppampattu" },
      { id: 148, name: "Vikramasingapuram" },
      { id: 120, name: "Viluppuram" },
      { id: 128, name: "Virudhachalam" },
      { id: 131, name: "Virudhunagar" },
      { id: 184, name: "Viswanatham" },
    ],
  },
  {
    state_id: 110,
    state_name: "Telangana",
    cities: [
      { id: 1014, name: "Adilabad" },
      { id: 1311, name: "Armur" },
      { id: 1032, name: "Bellampalle" },
      { id: 1035, name: "Bhadrachalam" },
      { id: 1037, name: "Bhainsa" },
      { id: 1033, name: "Bhongir" },
      { id: 1021, name: "Bodhan" },
      { id: 1040, name: "Farooqnagar" },
      { id: 1029, name: "Gadwal" },
      { id: 1507, name: "Hanamkonda" },
      { id: 1006, name: "Hyderabad" },
      { id: 1233, name: "Isnapur" },
      { id: 1016, name: "Jagtial" },
      { id: 1036, name: "Jangaon" },
      { id: 1030, name: "Kagaznagar" },
      { id: 1019, name: "Kamareddy" },
      { id: 1008, name: "Karimnagar" },
      { id: 1011, name: "Khammam" },
      { id: 1024, name: "Koratla" },
      { id: 1018, name: "Kothagudem" },
      { id: 1046, name: "Kyathampalle" },
      { id: 1012, name: "Mahbubnagar" },
      { id: 1013, name: "Mancherial" },
      { id: 1023, name: "Mandamarri" },
      { id: 1043, name: "Manuguru" },
      { id: 1038, name: "Medak" },
      { id: 1683, name: "Medchal-malkajgiri" },
      { id: 1017, name: "Miryalaguda" },
      { id: 1045, name: "Nagarkurnool" },
      { id: 1682, name: "Nalgonda" },
      { id: 1039, name: "Narayanpet" },
      { id: 1020, name: "Nirmal" },
      { id: 1009, name: "Nizamabad" },
      { id: 1022, name: "Palvancha" },
      { id: 1230, name: "Patancheru" },
      { id: 1010, name: "Ramagundam" },
      { id: 1041, name: "Sadasivpet" },
      { id: 1031, name: "Sangareddy" },
      { id: 1228, name: "Secunderabad" },
      { id: 1027, name: "Siddipet" },
      { id: 1025, name: "Sircilla" },
      { id: 1015, name: "Suryapet" },
      { id: 1026, name: "Tandur" },
      { id: 1034, name: "Vikarabad" },
      { id: 1028, name: "Wanaparthy" },
      { id: 1007, name: "Warangal" },
      { id: 1042, name: "Yellandu" },
    ],
  },
  {
    state_id: 125,
    state_name: "Texas",
    cities: [
      { id: 1451, name: "Aransas Pass" },
      { id: 1274, name: "Cedar Park" },
      { id: 1267, name: "Houston" },
      { id: 1490, name: "Irving" },
      { id: 1606, name: "Magnolia" },
      { id: 1773, name: "Marshall" },
      { id: 1638, name: "Mineral Wells" },
      { id: 1461, name: "The Woodlands City" },
    ],
  },
  {
    state_id: 162,
    state_name: "Thurgau",
    cities: [{ id: 1350, name: "Frauenfeld" }],
  },
  { state_id: 177, state_name: "Tokyo", cities: [{ id: 1429, name: "Tokyo" }] },
  {
    state_id: 88,
    state_name: "Tripura",
    cities: [
      { id: 84, name: "Agartala" },
      { id: 89, name: "Belonia" },
      { id: 86, name: "Dharmanagar" },
      { id: 88, name: "Kailasahar" },
      { id: 90, name: "Khowai" },
      { id: 87, name: "Pratapgarh" },
      { id: 85, name: "Udaipur" },
    ],
  },
  {
    state_id: 171,
    state_name: "Trøndelag",
    cities: [{ id: 1386, name: "Trondheim" }],
  },
  {
    state_id: 294,
    state_name: "Tula Oblast",
    cities: [{ id: 1747, name: "Tula" }],
  },
  {
    state_id: 183,
    state_name: "Tyne And Wear",
    cities: [
      { id: 1437, name: "Newcastle Upon Tyne" },
      { id: 1771, name: "North Shields" },
      { id: 1612, name: "South Shields" },
    ],
  },
  { state_id: 262, state_name: "Ulsan", cities: [{ id: 1636, name: "Ulsan" }] },
  {
    state_id: 239,
    state_name: "Ulster",
    cities: [{ id: 1562, name: "Belfast" }],
  },
  {
    state_id: 236,
    state_name: "Upper Carniola",
    cities: [{ id: 1557, name: "Jesenice" }],
  },
  {
    state_id: 298,
    state_name: "Upper Nazareth",
    cities: [{ id: 1769, name: "Nof Hagalil" }],
  },
  {
    state_id: 107,
    state_name: "Uttarakhand",
    cities: [
      { id: 744, name: "Bageshwar" },
      { id: 727, name: "Dehradun" },
      { id: 729, name: "Haldwani-cum-Kathgodam" },
      { id: 728, name: "Haridwar" },
      { id: 731, name: "Kashipur" },
      { id: 737, name: "Manglaur" },
      { id: 739, name: "Mussoorie" },
      { id: 741, name: "Nagla" },
      { id: 738, name: "Nainital" },
      { id: 742, name: "Pauri" },
      { id: 736, name: "Pithoragarh" },
      { id: 735, name: "Ramnagar" },
      { id: 734, name: "Rishikesh" },
      { id: 732, name: "Roorkee" },
      { id: 733, name: "Rudrapur" },
      { id: 743, name: "Sitarganj" },
      { id: 730, name: "Srinagar" },
      { id: 740, name: "Tehri" },
    ],
  },
  {
    state_id: 108,
    state_name: "Uttar Pradesh",
    cities: [
      { id: 846, name: "Achhnera" },
      { id: 748, name: "Agra" },
      { id: 754, name: "Aligarh" },
      { id: 751, name: "Allahabad" },
      { id: 752, name: "Amroha" },
      { id: 1362, name: "Auraiya" },
      { id: 775, name: "Azamgarh" },
      { id: 1736, name: "Baghpat" },
      { id: 766, name: "Bahraich" },
      { id: 1358, name: "Banda" },
      { id: 1574, name: "Barabanki" },
      { id: 1320, name: "Baraut" },
      { id: 1278, name: "Bareilly" },
      { id: 1573, name: "Bhadohi" },
      { id: 1553, name: "Bijnor" },
      { id: 1688, name: "Bindki" },
      { id: 1322, name: "Budaun" },
      { id: 1245, name: "Bulandshahr" },
      { id: 773, name: "Chandausi" },
      { id: 1347, name: "Deoria" },
      { id: 1510, name: "Domariyaganj" },
      { id: 763, name: "Etawah" },
      { id: 1363, name: "Faizabad" },
      { id: 1296, name: "Faridabad" },
      { id: 1364, name: "Farrukhabad" },
      { id: 1572, name: "Fatehpur" },
      { id: 818, name: "Fatehpur Sikri" },
      { id: 747, name: "Firozabad" },
      { id: 1256, name: "Gauriganj" },
      { id: 1220, name: "Ghaziabad" },
      { id: 1361, name: "Ghazipur" },
      { id: 1552, name: "Gonda" },
      { id: 1366, name: "Gorakhpur" },
      { id: 1250, name: "Greater-Noida" },
      { id: 762, name: "Hapur" },
      { id: 774, name: "Hardoi " },
      { id: 1378, name: "Jaunpur" },
      { id: 758, name: "Jhansi" },
      { id: 794, name: "Kalpi" },
      { id: 746, name: "Kanpur" },
      { id: 1533, name: "Kanth" },
      { id: 776, name: "Khair" },
      { id: 1539, name: "Kushinagar" },
      { id: 789, name: "Laharpur" },
      { id: 769, name: "Lakhimpur" },
      { id: 854, name: "Lalganj" },
      { id: 824, name: "Lal Gopalganj Nindaura" },
      { id: 772, name: "Lalitpur" },
      { id: 823, name: "Lar" },
      { id: 757, name: "Loni" },
      { id: 745, name: "Lucknow" },
      { id: 1343, name: "Mainpuri" },
      { id: 802, name: "Mathura" },
      { id: 749, name: "Meerut" },
      { id: 862, name: "Mirzapur" },
      { id: 761, name: "Modinagar" },
      { id: 753, name: "Moradabad" },
      { id: 1359, name: "Muzaffarnagar" },
      { id: 1352, name: "Muzaffarpur" },
      { id: 779, name: "Nagina" },
      { id: 783, name: "Najibabad" },
      { id: 845, name: "Nakur" },
      { id: 798, name: "Nanpara" },
      { id: 843, name: "Naraura" },
      { id: 816, name: "Naugawan Sadat" },
      { id: 815, name: "Nautanwa" },
      { id: 804, name: "Nawabganj" },
      { id: 799, name: "Nehtaur" },
      { id: 861, name: "Niwai" },
      { id: 756, name: "Noida" },
      { id: 806, name: "Noorpur" },
      { id: 860, name: "Obra" },
      { id: 765, name: "Orai" },
      { id: 801, name: "Padrauna" },
      { id: 811, name: "Palia Kalan" },
      { id: 853, name: "Parasi" },
      { id: 856, name: "Phulpur" },
      { id: 826, name: "Pihani" },
      { id: 771, name: "Pilibhit" },
      { id: 785, name: "Pilkhuwa" },
      { id: 841, name: "Powayan" },
      { id: 1360, name: "Pratapgarh" },
      { id: 1406, name: "Prayagraj" },
      { id: 859, name: "Pukhrayan" },
      { id: 808, name: "Puranpur" },
      { id: 837, name: "PurqUrban Agglomerationzi" },
      { id: 852, name: "Purwa" },
      { id: 768, name: "Rae Bareli" },
      { id: 760, name: "Rampur" },
      { id: 833, name: "Rampur Maniharan" },
      { id: 822, name: "Rasra" },
      { id: 793, name: "Rath" },
      { id: 786, name: "Renukoot" },
      { id: 847, name: "Reoti" },
      { id: 819, name: "Robertsganj" },
      { id: 809, name: "Rudauli" },
      { id: 827, name: "Rudrapur" },
      { id: 821, name: "Sadabad" },
      { id: 849, name: "Safipur" },
      { id: 755, name: "Saharanpur" },
      { id: 844, name: "Sahaspur" },
      { id: 792, name: "Sahaswan" },
      { id: 857, name: "Sahawar" },
      { id: 832, name: "Sahjanwa" },
      { id: 850, name: "Saidpur" },
      { id: 764, name: "Sambhal" },
      { id: 831, name: "Samdhan" },
      { id: 858, name: "Samthar" },
      { id: 842, name: "Sandi" },
      { id: 796, name: "Sandila" },
      { id: 797, name: "Sardhana" },
      { id: 800, name: "Seohara" },
      { id: 781, name: "Shahabad, Hardoi" },
      { id: 817, name: "Shahabad, Rampur" },
      { id: 835, name: "Shahganj" },
      { id: 759, name: "Shahjahanpur" },
      { id: 780, name: "Shamli" },
      { id: 828, name: "Shamsabad, Agra" },
      { id: 838, name: "Shamsabad, Farrukhabad" },
      { id: 791, name: "Sherkot" },
      { id: 814, name: "Shikarpur, Bulandshahr" },
      { id: 784, name: "Shikohabad" },
      { id: 855, name: "Shishgarh" },
      { id: 803, name: "Siana" },
      { id: 848, name: "Sikanderpur" },
      { id: 782, name: "Sikandrabad" },
      { id: 807, name: "Sikandra Rao" },
      { id: 825, name: "Sirsaganj" },
      { id: 851, name: "Sirsi" },
      { id: 770, name: "Sitapur" },
      { id: 1527, name: "Sonebhadra" },
      { id: 829, name: "Soron" },
      { id: 777, name: "Sultanpur" },
      { id: 834, name: "Sumerpur" },
      { id: 830, name: "SUrban Agglomerationr" },
      { id: 778, name: "Tanda" },
      { id: 805, name: "Thakurdwara" },
      { id: 810, name: "Thana Bhawan" },
      { id: 790, name: "Tilhar" },
      { id: 839, name: "Tirwaganj" },
      { id: 836, name: "Tulsipur" },
      { id: 795, name: "Tundla" },
      { id: 787, name: "Ujhani" },
      { id: 767, name: "Unnao" },
      { id: 820, name: "Utraula" },
      { id: 750, name: "Varanasi" },
      { id: 788, name: "Vrindavan" },
      { id: 840, name: "Warhapur" },
      { id: 812, name: "Zaidpur" },
      { id: 813, name: "Zamania" },
    ],
  },
  {
    state_id: 179,
    state_name: "Varese",
    cities: [
      { id: 1599, name: "Caronno Pertusella" },
      { id: 1434, name: "Gallarate" },
      { id: 1503, name: "Gorla Minore" },
      { id: 1436, name: "Sumirago" },
    ],
  },
  {
    state_id: 264,
    state_name: "Vaud",
    cities: [
      { id: 1651, name: "Lausanne" },
      { id: 1709, name: "Rolle" },
    ],
  },
  {
    state_id: 151,
    state_name: "Vestfold Og Telemark",
    cities: [{ id: 1303, name: "Sandefjord" }],
  },
  {
    state_id: 184,
    state_name: "Vestland",
    cities: [{ id: 1438, name: "Bergen" }],
  },
  {
    state_id: 285,
    state_name: "Victoria",
    cities: [{ id: 1720, name: "Melbourne" }],
  },
  {
    state_id: 279,
    state_name: "Vienna",
    cities: [{ id: 1693, name: "Vienna" }],
  },
  {
    state_id: 243,
    state_name: "Virginia",
    cities: [{ id: 1589, name: "Manassas" }],
  },
  {
    state_id: 240,
    state_name: "Vorarlberg",
    cities: [
      { id: 1711, name: "Höchst" },
      { id: 1563, name: "Lustenau" },
    ],
  },
  {
    state_id: 296,
    state_name: "Wales",
    cities: [{ id: 1749, name: "Wrexham" }],
  },
  {
    state_id: 169,
    state_name: "Washington",
    cities: [
      { id: 1384, name: "Everett" },
      { id: 1625, name: "Menomonee Falls" },
    ],
  },
  {
    state_id: 117,
    state_name: "West Bengal",
    cities: [
      { id: 1218, name: "Adra" },
      { id: 1199, name: "AlipurdUrban Agglomerationr" },
      { id: 1194, name: "Arambagh" },
      { id: 1178, name: "Asansol" },
      { id: 1185, name: "Baharampur" },
      { id: 1188, name: "Balurghat" },
      { id: 1192, name: "Bankura" },
      { id: 1551, name: "Barasat" },
      { id: 1422, name: "Bardhaman" },
      { id: 1541, name: "Bolpur" },
      { id: 1768, name: "Budge Budge" },
      { id: 1276, name: "Chandannagar" },
      { id: 1577, name: "Cooch Behar" },
      { id: 1732, name: "Dankuni" },
      { id: 1195, name: "Darjiling" },
      { id: 1244, name: "Durgapur" },
      { id: 1182, name: "English Bazar" },
      { id: 1201, name: "Gangarampur" },
      { id: 1189, name: "Habra" },
      { id: 1775, name: "Haldia" },
      { id: 1241, name: "Hooghly" },
      { id: 1237, name: "Howrah" },
      { id: 1183, name: "Hugli-Chinsurah" },
      { id: 1186, name: "Jalpaiguri" },
      { id: 1200, name: "Jhargram" },
      { id: 1202, name: "Kalimpong" },
      { id: 1179, name: "Kharagpur" },
      { id: 1176, name: "Kolkata" },
      { id: 1690, name: "Krishnanagar" },
      { id: 1216, name: "Mainaguri" },
      { id: 1212, name: "Malda" },
      { id: 1214, name: "Mathabhanga" },
      { id: 1190, name: "Medinipur" },
      { id: 1207, name: "Memari" },
      { id: 1217, name: "Monoharpur" },
      { id: 1203, name: "Murshidabad" },
      { id: 1196, name: "Nabadwip" },
      { id: 1181, name: "Naihati" },
      { id: 1215, name: "Panchla" },
      { id: 1211, name: "PandUrban Agglomeration" },
      { id: 1582, name: "Panskura" },
      { id: 1208, name: "Paschim Punropara" },
      { id: 1193, name: "Purulia" },
      { id: 1180, name: "Raghunathganj" },
      { id: 1213, name: "Raghunathpur" },
      { id: 1184, name: "Raiganj" },
      { id: 1206, name: "Rampurhat" },
      { id: 1191, name: "Ranaghat" },
      { id: 1204, name: "Sainthia" },
      { id: 1187, name: "Santipur" },
      { id: 1177, name: "Siliguri" },
      { id: 1209, name: "Sonamukhi" },
      { id: 1219, name: "Srirampore" },
      { id: 1198, name: "Suri" },
      { id: 1205, name: "Taki" },
      { id: 1197, name: "Tamluk" },
      { id: 1210, name: "Tarakeswar" },
    ],
  },
  {
    state_id: 149,
    state_name: "Western Province",
    cities: [{ id: 1301, name: "Colombo" }],
  },
  {
    state_id: 250,
    state_name: "West Midlands",
    cities: [
      { id: 1705, name: "Birmingham" },
      { id: 1603, name: "Halesowen" },
    ],
  },
  {
    state_id: 167,
    state_name: "West Sussex",
    cities: [{ id: 1381, name: "Burgess Hill" }],
  },
  {
    state_id: 137,
    state_name: "Wisconsin",
    cities: [
      { id: 1355, name: "Marinette" },
      { id: 1288, name: "Milwaukee" },
      { id: 1472, name: "Waukesha" },
    ],
  },
  {
    state_id: 123,
    state_name: "Wurttemberg",
    cities: [
      { id: 1263, name: "Baden" },
      { id: 1266, name: "Fellbach" },
    ],
  },
  {
    state_id: 276,
    state_name: "Yongkang",
    cities: [{ id: 1685, name: "Tainan" }],
  },
  {
    state_id: 237,
    state_name: "Yorkshire",
    cities: [{ id: 1559, name: "Hull" }],
  },
  {
    state_id: 189,
    state_name: "Zaragoza",
    cities: [{ id: 1446, name: "Zaragoza" }],
  },
  {
    state_id: 159,
    state_name: "Zhejiang",
    cities: [
      { id: 1687, name: "Jiaxing" },
      { id: 1340, name: "Ningbo" },
      { id: 1652, name: "Wenzhou" },
      { id: 1339, name: "Zhuji" },
    ],
  }
];
