export const ANNOUNCEMENT_TEXT =
  "Now expanding Internationally \u2014 meet us at Intersec Dubai 2026 from 12\u201314 January, Stand no. SR-D24, Dubai World Trade Centre";

export const initialMainNavs = [
  "/",
  "/aboutus",
  "/contactus",
  "/for-vendors",
  "/vendor/all",
  "/hotel-vendor",
  "/solutions",
  "/blogs",
  "/validate-otp",
  "/forget-password",
  "/privacypolicy",
  "/terms-of-use",
  "/products",
  "/dashboard/vendor/inquiries-details",
  "/dashboard/buyer/rfq-management-vendor/vendor-profile",
  "/newHomePageDesign",
  "/ai-tools",
  "/ai-tools/boq-simplification",
  "/ai-tools/cost-estimation",
  "/ai-tools/tender-summary",
  "/ai-tools/technical-summary",
  "/insights",
  "/insights/events",
  "/insights/news",
  "/insights/procurement-guide",
  "/insights/ai-procurement",
  "/insights/epc-trends",
  "/modules",
  "/modules/boq",
  "/modules/rfq",
  "/modules/payments",
  "/modules/evaluation",
  "/modules/negotiation",
  "/modules/vendors",
  "/work-with-us",
  "/work-with-us/TeamTimeline",
  "/work-with-us/careers",
];

export const roleMenus = {
  admin: [
    { href: "/dashboard/admin/editprofile", label: "Profile", targetMenu: "popup", icon: "person" },
    { href: "/dashboard/admin", label: "Dashboard", targetMenu: "nav" },
    { href: "/dashboard/admin/account-management/manage-accounts", label: "User Management", targetMenu: "nav" },
    { href: "/dashboard/admin/hospitality-manager", label: "Hospitality Network", targetMenu: "nav" },
  ],
  buyer: [
    { href: "/dashboard/buyer", label: "Dashboard", targetMenu: "nav" },
    { href: "/vendor/all", label: "Create RFQ", targetMenu: "nav" },
    { href: "/dashboard/buyer/rfq-management", label: "RFQ Management", targetMenu: "nav" },
    { href: "/dashboard/buyer/technical-evaluation", label: "Tech Evaluation", targetMenu: "nav" },
    { href: "/dashboard/buyer/quote-compare", label: "Quote Compare", targetMenu: "nav" },
    { href: "/dashboard/buyer/arc-committee", label: "ARC Committee", targetMenu: "nav" },
    { href: "/dashboard/buyer/purchase-order", label: "Purchase Orders", targetMenu: "nav" },
    { href: "/dashboard/buyer/editprofile", label: "Profile", targetMenu: "popup", icon: "person" },
    { href: "/dashboard/buyer/vendor-management", label: "Vendor Management", targetMenu: "popup", icon: "people" },
  ],
  management: [
    { href: "/dashboard/management", label: "Dashboard", targetMenu: "nav" },
    { href: "/vendor/all", label: "Create RFQ", targetMenu: "nav" },
    { href: "/dashboard/buyer/rfq-management", label: "RFQ Management", targetMenu: "nav" },
    { href: "/dashboard/buyer/technical-evaluation", label: "Tech Evaluation", targetMenu: "nav" },
    { href: "/dashboard/buyer/quote-compare", label: "Quote Compare", targetMenu: "nav" },
    { href: "/dashboard/buyer/arc-committee", label: "ARC Committee", targetMenu: "nav" },
    { href: "/dashboard/buyer/purchase-order", label: "Purchase Orders", targetMenu: "nav" },
    { href: "/dashboard/management/editprofile", label: "Profile", targetMenu: "popup", icon: "person" },
    { href: "/dashboard/management/project-management", label: "Project Management", targetMenu: "popup", icon: "folder" },
    { href: "/dashboard/buyer/vendor-management", label: "Vendor Management", targetMenu: "popup", icon: "people" },
  ],
  finance: [
    { href: "/dashboard/buyer/quote-compare", label: "Quote Comparison", targetMenu: "nav" },
    { href: "/dashboard/buyer/purchase-order", label: "Purchase Orders", targetMenu: "nav" },
    { href: "/dashboard/finance/editprofile", label: "Profile", targetMenu: "popup", icon: "person" },
    { href: "/dashboard/finance", label: "Dashboard", targetMenu: "popup", icon: "grid" },
  ],
  engineering: [
    { href: "/dashboard/buyer/technical-evaluation", label: "Technical Evaluation", targetMenu: "nav" },
    { href: "/dashboard/engineering/editprofile", label: "Profile", targetMenu: "popup", icon: "person" },
    { href: "/dashboard/engineering", label: "Dashboard", targetMenu: "popup", icon: "grid" },
  ],
  vendor: [
    { href: "/dashboard/vendor/editprofile", label: "Profile", targetMenu: "popup", icon: "person" },
    { href: "/dashboard/vendor/product-management", label: "Product Management", targetMenu: "nav" },
    { href: "/dashboard/vendor/inquiries-received", label: "Received Inquiries", targetMenu: "nav" },
    { href: "/dashboard/vendor/reviews-ratings", label: "Reviews & Ratings", targetMenu: "nav" },
    { href: "/dashboard/vendor/order-book", label: "Order Book", targetMenu: "nav" },
  ],
};

export const websiteMenu = [
  {
    label: "Our Offerings",
    type: "dropdown",
    options: [
      { label: "BOQ Understanding & Simplification", href: "/modules/boq" },
      { label: "RFQ Creation & Management", href: "/modules/rfq" },
      { label: "Supplier Discovery & Vendor Management", href: "/modules/vendors" },
      { label: "Technical & Commercial Evaluation", href: "/modules/evaluation" },
      { label: "Negotiation Management", href: "/modules/negotiation" },
      { label: "PO & Payment Lifecycle Management", href: "/modules/payments" },
    ],
  },
  {
    label: "Who We Serve",
    type: "dropdown",
    options: [
      {
        label: "Stakeholders",
        type: "nested-dropdown",
        options: [
          { label: "EPCs / Contractors", href: "/who-we-serve/stakeholders/epcs" },
          { label: "Turnkey Project Firms", href: "/who-we-serve/stakeholders/turnkey" },
          { label: "Project Consultants", href: "/who-we-serve/stakeholders/consultants" },
          { label: "Industrial Clients", href: "/who-we-serve/stakeholders/industrial-clients" },
          { label: "Vendors & OEMs", href: "/for-vendors" },
        ],
      },
      {
        label: "Industries We Serve",
        type: "nested-dropdown",
        options: [
          { label: "Power", href: "/who-we-serve/industries/power" },
          { label: "Energy", href: "/who-we-serve/industries/energy" },
          { label: "Petrochemical & Chemical", href: "/who-we-serve/industries/petrochemical" },
          { label: "Steel & Cement", href: "/who-we-serve/industries/steel-cement" },
          { label: "Infrastructure", href: "/who-we-serve/industries/infrastructure" },
          { label: "Heavy Engineering & Machine Tools", href: "/who-we-serve/industries/heavy-equipment" },
          { label: "Marine & Mining", href: "/who-we-serve/industries/marine-mining" },
        ],
      },
      {
        label: "Disciplines We Cover",
        type: "nested-dropdown",
        options: [
          { label: "Electrical", href: "/solutions/electrical" },
          { label: "Mechanical", href: "/solutions/mechanical" },
          { label: "Civil", href: "/solutions/civil" },
          { label: "HVAC", href: "/solutions/hvac" },
          { label: "Fire & Safety", href: "/solutions/fire-engineering" },
          { label: "Chemical", href: "/solutions/chemical" },
        ],
      },
    ],
  },
  {
    label: "Tools",
    type: "dropdown",
    options: [
      { label: "Vendor Discovery", href: "/vendor/all" },
      { label: "BOQ Simplifier", href: "/ai-tools/boq-simplification" },
      { label: "Project Cost Estimator", href: "/ai-tools/cost-estimation" },
      { label: "Tender Summary", href: "/ai-tools/tender-summary" },
      { label: "Technical Document Summary", href: "/ai-tools/technical-summary" },
    ],
  },
  {
    label: "Insights & Resources",
    type: "dropdown",
    options: [
      { label: "Blogs", href: "https://letsworkwise.com/blog/", external: true },
      { label: "Events", href: "/insights/events" },
      { label: "Procurement Guide for Project & Purchase Managers", href: "/insights/procurement-guide" },
      { label: "AI in Procurement - Use Cases", href: "javascript:void(0)", upcoming: true },
      { label: "Trends in EPC Procurement", href: "/insights/epc-trends" },
      { label: "Workwise in News", href: "/insights/news" },
    ],
  },
  {
    label: "Work With Us",
    type: "dropdown",
    options: [
      { label: "Meet the Team", href: "/work-with-us/TeamTimeline" },
      { label: "We are hiring!", href: "/work-with-us/careers" },
      { label: "Earn With Us", href: "/earn-with-us/EarnWithUs" },
      { label: "Contact Us", href: "/contactus" },
    ],
  },
  {
    label: "Pricing",
    type: "dropdown",
    options: [
      { label: "Buyer pricing", href: "/pricing", action: "buyer-pricing" },
      { label: "Supplier plans", href: "/pricing", action: "supplier-pricing" },
      { label: "Claim Pilot Project Access for Free", href: "/pilot-project" },
    ],
  },
];
